### ISSUE TITLE
Update of Testimonials Section 

### ISSUE THREAD

**Issue by rajatsinghal02** [Luson045/medi-connect#101]
I want to update the testimonial section of the website. It is unplaced and have many UI issues.

![Screenshot_20241003_012449.jpg](https://github.com/user-attachments/assets/5f200c56-5454-4f27-96fe-251bcc78bcf8)

@Luson045 Please assign this issue to me. I want to solve this issue.

**Comment by Luson045** [comment]
@rajatsinghal02 others are working on it
