### ISSUE TITLE
Footer Update for Mobile Responsive Website 

### ISSUE THREAD

**Issue by rajatsinghal02** [Luson045/medi-connect#102]
I want to update the footer of the website as there is no such space in footer so it is not readable to user and not attractive.

![Screenshot_20241003_012644.jpg](https://github.com/user-attachments/assets/11cfc0fa-7ff0-4602-b7c1-ada23ad5f8c4)

@Luson045 Please assign this issue to me.

**Comment by Luson045** [comment]
@rajatsinghal02 assigned! complete it by tomorrow...👍
