### ISSUE TITLE
Redesign the Research and Data section on the landing page

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#103]
Give the research and data section a professional look, use some proper design and animations

**Comment by ParasY1724** [comment]
Please Assign this task to me

**Comment by Luson045** [comment]
@ParasY1724 this scrollbar was changed in your PR , can you change it back, also use a colour similar to theme
<img width="960" alt="image" src="https://github.com/user-attachments/assets/1e5182e6-268e-437c-baf7-1df9048a1e1d">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/892893b1-af38-4934-8600-99a502fc9327">

**Comment by ParasY1724** [comment]
@Luson045  Ok !!

**Comment by ParasY1724** [comment]
@Luson045  Check #160
