### ISSUE TITLE
Change the registration form according to the details required for the hospital and users

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#105]
as both hospital and user have different fields i their database, we need to handle taking those details when a hospital or a user registers... You can find the required fields in server/model  just add input for the items which are there in the model but not in the UI

example we need to take input of PIN code from the hospital but it is not there in the register page as of now..

first  you can merge conflicts of your previous pr and then you can do this one

_Originally posted by @Luson045 in https://github.com/Luson045/medi-connect/issues/70#issuecomment-2389052029_

**Comment by lade6501** [comment]
Hi @Luson045 have started working on above, please confirm it's still planned or closed ?

**Comment by Luson045** [comment]
yeah you can start working on it, make sure you take the pincode of hospital during registration and convert it into lat and long and then it is saved in the db

**Comment by lade6501** [comment]
Hi @Luson045 , I checked feasibility of  this issue, we firstly  need to create  separate `Login` and `Register` component. Cause form fields are getting mix and it will involve too much conditional rendering.

**Comment by lade6501** [comment]
Hi @Luson045, any suggestion's on above ?

**Comment by Luson045** [comment]
@lade6501 if you can tackle the issue then you can work on it. In case of registration form, these details are a must to fill, because these information are crucial for us. You can change the format of registration form to make it fit in a single page for desktop but for phone you cannot do that...

So I guess you can make a multistep form for registration.

**Comment by lade6501** [comment]
Yes, will go with multistep form approach and separate component for `Login` and `Register`

**Comment by lade6501** [comment]
Sorry for the delay, have almost completed the work testing few scenarios before raising PR, will raise PR by EOD. Thanks! for being patient.

**Comment by Luson045** [comment]
great!! btw the pincode to latitude thing is already fixed so take care of that you might have some merge conflicts during the PR
