### ISSUE TITLE
redesign Instant-opd page

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [Luson045/medi-connect#11]
![Medi-Connect - Google Chrome 01-10-2024 10_42_48 AM](https://github.com/user-attachments/assets/cf5c430f-2e18-426d-832b-dbcc5dd3d029)

i just want to redesign it.

**Comment by Luson045** [comment]
sure, we're currently working on ui so for the color combination you can disscuss with other contributors there

**Comment by Mukesh-ghildiyal** [comment]
#17  
![Welcome to medi-connect UI Discussions! · Luson045_medi-connect · Discussion #12 - Google Chrome 01-10-2024 09_24_08 PM](https://github.com/user-attachments/assets/cdd2bdc9-64e5-421c-8047-32b439047999)
 now i just add the background color according to your theme

**Comment by Luson045** [comment]
okay looks great, one final thing make the size of all the input boxes similar to each other

**Comment by Mukesh-ghildiyal** [comment]
okk sure

**Comment by Mukesh-ghildiyal** [comment]
![Welcome to medi-connect UI Discussions! · Luson045_medi-connect · Discussion #12 - Google Chrome 01-10-2024 09_24_08 PM](https://github.com/user-attachments/assets/071583d5-74d7-4716-a31f-edd65f931585)
 now if its okay okay so i can raise the pr

**Comment by Mukesh-ghildiyal** [comment]
![Uploading Medi-Connect - Google Chrome 01-10-2024 09_50_31 PM.png…]()

**Comment by Mukesh-ghildiyal** [comment]
![Medi-Connect - Google Chrome 01-10-2024 09_50_31 PM](https://github.com/user-attachments/assets/ea44ef28-033c-4198-ab1a-805fab816319)
 now i have done all the changes

**Comment by Luson045** [comment]
great, have you added it in your pr? you can proceed with that now

**Comment by Luson045** [comment]
completed
