### ISSUE TITLE
Design the hero section

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#110]
add transparent images, use better fonts etc and make the landing page attractive
take references from these and make sure to keep it responsive... if the design is not very good, it'll be rejected
![image](https://github.com/user-attachments/assets/ddef1ec6-b3be-4c9d-89bb-981ac59047db)
![image](https://github.com/user-attachments/assets/4f7e318d-e926-4f14-a0ff-abf946ddd45e)
![image](https://github.com/user-attachments/assets/224c48ab-527b-49fe-b812-da505dd9c9a8)
![image](https://github.com/user-attachments/assets/9a301878-40c9-4588-96a4-7c88f61e6f40)
![image](https://github.com/user-attachments/assets/081fd186-626e-4d63-8aea-39c6f548bf25)
![image](https://github.com/user-attachments/assets/a38b61ef-f97a-4453-b3b3-7786597f5cd1)
![image](https://github.com/user-attachments/assets/e357ea8d-1572-46ba-b6b6-e3ad373b67ca)
![image](https://github.com/user-attachments/assets/799b64aa-dc87-4020-aa2a-150310e88a71)

**Comment by shibasarkar** [comment]
@Luson045  can you please assign this to me

**Comment by Luson045** [comment]
@shibasarkar done, but try to complete it by the end of tomorrow

**Comment by shibasarkar** [comment]
ok thank you

**Comment by shibasarkar** [comment]
@Luson045 I have a confusion , can you tell me that I need to fork the repo again or just work on my existing one
?

**Comment by Luson045** [comment]
work on the existing one @shibasarkar and please keep this in mind , please dont submit any basic html css design, make it look a little professional
<img width="659" alt="image" src="https://github.com/user-attachments/assets/89b5ad99-76b3-435d-83b7-3d27533d16af">

**Comment by shibasarkar** [comment]
ok

**Comment by shibasarkar** [comment]
@Luson045 should I add navbar acordinly hero-section or only modify the hero-section?

**Comment by shibasarkar** [comment]
@Luson045  is this ok 
![Screenshot 2024-10-04 124418](https://github.com/user-attachments/assets/81d7ed8b-fb6a-46f9-b3e8-fe5577942917)
![Screenshot 2024-10-04 124439](https://github.com/user-attachments/assets/ad7efb6b-9005-4d04-8871-11cfde18f24d)

**Comment by Luson045** [comment]
Looking great but green is not matching with the logo right?@shibasarkar

**Comment by Luson045** [comment]
Yeah better 👍🏻

**Comment by shibasarkar** [comment]
@Luson045 I think we need to use a single color palate or single framework for style enhancement also the basic HTML structure are not decorated well

**Comment by shibasarkar** [comment]
@Luson045 can you help me 
how do I create new PR 
![Screenshot 2024-10-04 144851](https://github.com/user-attachments/assets/02e3f30f-c8d4-421b-8c51-ce8c669c660e)

**Comment by Luson045** [comment]
in your local repo copy the changes somewhere in your pc,  delete this pr cancel the changes you made and the fetch the latest code and update it accordingly

**Comment by Luson045** [comment]
@shibasarkar 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/3ff800eb-6e58-4d39-a70f-97313b213228">
try to implement this theme

**Comment by Luson045** [comment]
@shibasarkar first complete the redesign of home page.. ![Screenshot_2024-10-04-17-34-26-89_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/87b9ef47-e75c-402c-9d0a-63666aa6d237)

It's not responsive, the above portion on the text is not coming in Android..

Also the design still don't look very appealing. Work on it.
