### ISSUE TITLE
fix mobile nabar ui bug

### ISSUE THREAD

**Issue by deji-ice** [Luson045/medi-connect#118]
There is an issue with the navbar on mobile devices that needs to be fixed. Here are the details:

Current Behavior:
The logo is not fully visible.
The mobile hamburger close icon is not fully displayed, leading to usability issues for users

Expected Behavior:
The logo should be fully visible on mobile devices.
The hamburger menu should open and close correctly without any visual or functional issues.

![Screen Shot 2024-10-03 at 13 44 09](https://github.com/user-attachments/assets/61d6db89-93c6-487d-a473-49a9f8eacdfb)

**Comment by Luson045** [comment]
okay you can work on it 👍 @deji-ice

**Comment by Luson045** [comment]
@deji-ice need update on this by tonight
