### ISSUE TITLE
FIX :  Login and Register Button Design

### ISSUE THREAD

**Issue by its-kumar-yash** [Luson045/medi-connect#120]
Login and Register button are not properly visible as they don't have any border or background color.

![image](https://github.com/user-attachments/assets/4e6bc85e-463c-4959-a0c5-cbff577313ba)

**Comment by Mefisto04** [comment]
hey @its-kumar-yash i want to contribute in this issue, can you assign this to me.

**Comment by Luson045** [comment]
@its-kumar-yash okay you can work on it but be fast, as a lot of work is going on in the login and register form.. outdated PR's won't be accepted

**Comment by its-kumar-yash** [comment]
@Luson045 okay

**Comment by its-kumar-yash** [comment]
Check now
