### ISSUE TITLE
[FEATURE] : Custom Cursor UI Implementation

### ISSUE THREAD

**Issue by Trevisx07** [Luson045/medi-connect#125]
Implementation of a custom cursor for the website. The default cursor could be replaced with a unique, more visually appealing design to enhance user interaction and improve the overall user experience.

Details:
- The custom cursor should align with the design and theme of the website.
- The cursor's design should be responsive and maintain usability on both desktop and mobile views.
- The custom cursor should have smooth transitions, not affect the site's performance, and be cross-browser compatible.

Examples For Reference:
![image](https://github.com/user-attachments/assets/7a01f16f-5e84-4770-9ae5-bc6bcb5a79e1)
![image](https://github.com/user-attachments/assets/b679e4a6-beb6-4589-9588-950dffb9d127)

**Comment by NawinKumarSharma** [comment]
@Trevisx07 can you assign me?

**Comment by Trevisx07** [comment]
@NawinKumarSharma Okay, I am assigning to you.

**Comment by NawinKumarSharma** [comment]
@Trevisx07 , can you review the pr #133
