### ISSUE TITLE
feat: Setup Docker & Docker Compose

### ISSUE THREAD

**Issue by geekyharsh05** [Luson045/medi-connect#127]
##### Setup Docker and Docker Compose to containerize the application and manage services efficiently. Enables consistent development and deployment across environments with predefined configurations.

Can you please add it under `hacktoberfest` label & assign it to me.

**Comment by Luson045** [comment]
check the PRs

**Comment by geekyharsh05** [comment]
@Luson045 I will add a multistage dockerfile

**Comment by geekyharsh05** [comment]
@Luson045 Are you using Docker Containers in prod with kubernetes?

**Comment by geekyharsh05** [comment]
@Luson045 The multistage file will reduce the final size of the image.

**Comment by geekyharsh05** [comment]
@Luson045 For reference: https://github.com/code100x/cms/pull/1371

**Comment by geekyharsh05** [comment]
No problem if you are happy with the current configs!

**Comment by Luson045** [comment]
I'd inform in a few days ok 👍🏻

**Comment by geekyharsh05** [comment]
@Luson045 Sure thanks I'll keep that in mind.
