### ISSUE TITLE
adding a "scroll-to-top button"

### ISSUE THREAD

**Issue by AnkitLuhar** [Luson045/medi-connect#128]
**Currently, users find it difficult to scroll back to the top of the page. To improve the user experience and make the website more user-friendly, I suggest adding a scroll-to-top button. This will enhance the website's interactivity and provide a more seamless navigation experience..**

**here is the current photo of the webpage:**

![Screenshot (936)](https://github.com/user-attachments/assets/940f6c39-176a-4749-9659-ae4c924d6e14)

![Screenshot (937)](https://github.com/user-attachments/assets/969d6b83-b7f6-4d56-8c1a-985fe95a99df)

### Assign this under the Hacktoberfest.

**Comment by AnkitLuhar** [comment]
@Luson045 assign this under the hackltoberfest.

**Comment by Luson045** [comment]
okay 👍
