### ISSUE TITLE
Readme.md and Contribution.md Changes

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [Luson045/medi-connect#13]
In your readme file basically given the wrong file and folder structure even those folders are not exist.

allocate me this task 
![Mukesh-ghildiyal_medi-connect_edit_ Medi-connect is an online hospital appointment booking website  Visit our website, find vulnerabilities and raise an issue - Google Chrome 01-10-2024 03_00_54 PM](https://github.com/user-attachments/assets/ff390fed-67b8-4a42-894d-1a31e2bd8146)

**Comment by Luson045** [comment]
okay but it would be very less, for a complete issue, so also cover the contribution.md file in this issue and enhance it too

**Comment by Mukesh-ghildiyal** [comment]
okk sure sir i will do

**Comment by Mukesh-ghildiyal** [comment]
@Luson045  #19  just merge this after reviewing

**Comment by Luson045** [comment]
completed
