### ISSUE TITLE
fixing the navbar UI

### ISSUE THREAD

**Issue by AnkitLuhar** [Luson045/medi-connect#130]
Currently, the navbar design doesn't look appealing. Please assign this issue to me, and I will update the navbar styling and UI to make it more user-friendly and interactive.

here is the S.S:

![Screenshot (936)](https://github.com/user-attachments/assets/bcfa042c-000c-4818-84a4-8d7a420eb9be)

### Assign under the HacktoberFest.

**Comment by AnkitLuhar** [comment]
@Luson045 assign this issue to me under the hacktoberfest24.

**Comment by Luson045** [comment]
issue #118 covers this @AnkitLuhar

**Comment by AnkitLuhar** [comment]
@Luson045 okay let them finish ,afterwards if the work is not satisfied then,i will work on  the navbar ui under the  modern-aesthics.
