### ISSUE TITLE
Make the navbar stick through the scroll through the landing page and improve styling

### ISSUE THREAD

**Issue by shrek-28** [Luson045/medi-connect#134]
The current navbar does not remain fixed when scrolling through the landing page, which can make navigation challenging for users. Implementing a sticky or fixed navbar will enhance user experience by keeping the navigation options accessible at all times, allowing users to easily access different sections of the page without needing to scroll back to the top. This improvement will help in maintaining a seamless browsing experience and improve overall usability.

**Comment by Luson045** [comment]
work is being done on that
