### ISSUE TITLE
Can design the better Navbar design.

### ISSUE THREAD

**Issue by dhruvjain23** [Luson045/medi-connect#137]
I want to participate in this project by contributing some new attractive design to the Navbar , also the navbar in hamburger menu has some issues but it assigns to other devloper, but I can design for both, for the desktop and also for responsiveness as per the user.

Can you please assign me this issue , you can also assigns me only for attractive design for navbar, as hamburger issue is already assigned to other.  but tell me in the comment section whether you assigns for bith topics or one.

Kindly assigns me this issue. @Luson045

**Comment by amrahs02** [comment]
Hey @dhruvjain23 i want to get into this , please assign this to me

**Comment by Luson045** [comment]
okay @dhruvjain23 
improve this in desktop view
<img width="960" alt="image" src="https://github.com/user-attachments/assets/112fe577-f327-4da8-ae90-8bb93d592608">
