### ISSUE TITLE
Improve the Navbar

### ISSUE THREAD

**Issue by MehediMubin** [Luson045/medi-connect#14]
![navbar](https://github.com/user-attachments/assets/584647b1-8ad8-49de-b5e1-55f394ad785f)
Enhance the current navigation bar to provide a better user experience and visual appeal.

**Comment by MehediMubin** [comment]
Hey @Luson045,
Can you please assign me to this task?
Thanks

**Comment by Luson045** [comment]
Assigned 👍

**Comment by Luson045** [comment]
@MehediMubin make the navbar disappear when scrolled down and appear when scrolled up

**Comment by MehediMubin** [comment]
@Luson045 I will do that. Also, I wanted to change the look of the navbar for mobile/tablet devices. Can I do that too?

**Comment by Luson045** [comment]
yeah, you're free to be creative

**Comment by Luson045** [comment]
@MehediMubin complete it by tonight. Also make sure that the PR that you give must be updated with the current status of the repo

**Comment by Luson045** [comment]
The issue is Outdated !!
