### ISSUE TITLE
[FEAT] Issue and PR template

### ISSUE THREAD

**Issue by Abhi0049k** [Luson045/medi-connect#140]
Description
We need to add standardized templates for issues and pull requests (PRs) to maintain consistency and improve the clarity of communication in our project. This will ensure that all contributors follow a structured approach when creating issues or submitting PRs.

**Comment by Abhi0049k** [comment]
@Luson045, Can you assign this issue to me?
and please add hacktoberfest and gssoc labels.
Thank you

**Comment by Luson045** [comment]
Not needed as of now.
