### ISSUE TITLE
redesign of registration and login page 

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [Luson045/medi-connect#141]
![improve registration ui](https://github.com/user-attachments/assets/99f0f2f6-ce0c-4ebc-82b6-da083562a99f)  

it shows all device's only column vice so also add responsive design based on screen as well need 
If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well

**Comment by Luson045** [comment]
Okay, but make sure the design is as expected and not outdated👍🏻

**Comment by Sureshwebdeveloper** [comment]
Ok bro thanks for assign to me 🙂

**Comment by Sureshwebdeveloper** [comment]
i am facing error to docker compose build 
![image](https://github.com/user-attachments/assets/9b387f3d-7af9-4059-95cb-438ef62eeab4)

i don't know how to fix help me how to solve issue

**Comment by Luson045** [comment]
@Sureshwebdeveloper try setting up without docker

**Comment by Sureshwebdeveloper** [comment]
> @Sureshwebdeveloper try setting up without docker

I have completed all of my code can I make pull request ? reopen issue

**Comment by Luson045** [comment]
design is outdated, a lot of chages have been made in registration form.
