### ISSUE TITLE
Mobile screen  navbar over flow to top nav bar 

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [Luson045/medi-connect#142]
![image](https://github.com/user-attachments/assets/9c7ab1d5-6cec-4547-9507-1916c4bb5807)

Mobile Screen Nav bar overflow to top nav bar also need a better ui as well
If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well

**Comment by Luson045** [comment]
Working on tht
