### ISSUE TITLE
Addition of Use Case Diagram to the README.md

### ISSUE THREAD

**Issue by shrek-28** [Luson045/medi-connect#145]
1. Add a visual representation of the system's use cases to the README.md to improve understanding of the application's functionalities.
2. Ensure the diagram clearly depicts the main actors, their roles, and interactions with the system.
3. Provide a brief explanation in the README.md to accompany the Use Case Diagram, explaining the key components and flows.
4. Ensure the diagram is properly formatted and easily viewable in the README.md on various platforms (e.g., GitHub).

**Comment by Luson045** [comment]
Okay 👍🏻
