### ISSUE TITLE
Can Add icons in the footer section

### ISSUE THREAD

**Issue by anmol-284** [Luson045/medi-connect#149]
I can add the icons in all the section in the footer

**Comment by Aaditya8C** [comment]
Can I work for this task?

**Comment by Luson045** [comment]
@Aaditya8C no

**Comment by anmol-284** [comment]
@Luson045 please look at the changes, i made it recently, please add hacktoberfest label

**Comment by Luson045** [comment]
yea i'll merge it soon. are you using url for the animations.. will it take time to load for slow internet @anmol-284

**Comment by anmol-284** [comment]
No, they are just gifs. no url has been used.
