### ISSUE TITLE
Redesign Existing Testimonials UI

### ISSUE THREAD

**Issue by vaishnav-3** [Luson045/medi-connect#153]
I want to participate in this project by contributing, 
The current testimonials UI has a zoom-out effect when the cursor hovers over a testimonial card, but it causes a visual issue where the top and bottom parts of the card are cut off.

https://github.com/user-attachments/assets/16fac9fd-d296-4047-8da6-22fe2d2da24b

**Comment by Luson045** [comment]
Ok 👍🏻
