### ISSUE TITLE
Improve Cursor Effect for Enhanced User Experience

### ISSUE THREAD

**Issue by AnkitLuhar** [Luson045/medi-connect#155]
**Problem:**
Current Issue: The current cursor effect on the website appears unappealing and does not provide a smooth user experience. This can detract from the overall aesthetics of the site and may affect user engagement.

### ##Proposed Changes:

1>Custom Cursor: Implement a custom cursor design that aligns with the website’s theme.

2>Hover Effects: Introduce hover effects on buttons and links to provide visual feedback. This can include:

- Background color changes

- Scale transformation for buttons

3>Smoother Transition: Ensure that all cursor effects and transitions are smooth and visually appealing.

here is the S.S:
![Screenshot (943)](https://github.com/user-attachments/assets/6a4ffe9a-ac45-4852-aed0-b44709127d10)

### Assign under the Hacktoberfest

**Comment by Luson045** [comment]
@AnkitLuhar okay
