### ISSUE TITLE
Implement Loader Page for Improved User Experience

### ISSUE THREAD

**Issue by AnkitLuhar** [Luson045/medi-connect#156]
**Problem:**

Current Issue: Currently, the website lacks a loading indicator, which can lead to confusion for users while they wait for pages to load or data to be fetched. This may result in a perceived delay and can negatively impact user experience.

### Proposed Changes:

1>Design a Loader: Create a visually appealing loader animation that reflects the branding and theme of the website. 

2>Loader Duration:

- Set a maximum duration for the loader to prevent it from appearing for too long.

- Consider adding a fade-out effect once the loading is complete.

here is the example of the Loader:

![image](https://github.com/user-attachments/assets/40f7b074-5da5-4090-b107-d6f147d5edae)

**Comment by AnkitLuhar** [comment]
@Luson045 assign this issue under the Hacktoberfest24.

**Comment by Luson045** [comment]
@AnkitLuhar okay, but since you are working on a lot of issues try to complete it fast
