### ISSUE TITLE
Want to correct the PIN validation in register form 

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#158]
the PIN validation in register form is wrong i want to correct it 
![image](https://github.com/user-attachments/assets/86ecfcb7-f290-47b2-ae48-af7c8b11661e)

**Comment by 17arindam** [comment]
@Luson045 can you assign me this issue?

**Comment by Luson045** [comment]
okay

**Comment by Somnath-Chattaraj** [comment]
@17arindam sorry to say that I have solved this issue and made a pr. Can you please let me assigned in your place.

**Comment by 17arindam** [comment]
@Somnath-Chattaraj Sorry but i have solved this issue too and i am raising the pr otherwise i would have
