### ISSUE TITLE
The Appointment form is not resetting after booking an apointment

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#159]
the appointment form should reset after one confirm book an appointment 
![image](https://github.com/user-attachments/assets/34b87fce-ee8a-4acc-a522-ec84c369ce0a)

**Comment by 17arindam** [comment]
@Luson045 can you assign me this issue

**Comment by Luson045** [comment]
1)after confirmation redirect to profile page. 
2)also cover the instant OPD result. Once the registration is confirmed, show a card with the details that is being returned from the backend

**Comment by 17arindam** [comment]
@Luson045 okayy
