### ISSUE TITLE
Redesign the logo

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#164]
As we've changed the project name to Med Space from Medi-connect we want a new logo for better branding
we need it as soon as possible

**Comment by BinaryBhakti** [comment]
I would love to do this. Do assign me the task.

**Comment by shibasarkar** [comment]
@Luson045 I have few options if you want i can share with you

**Comment by BinaryBhakti** [comment]
Yes Sure

**Comment by Luson045** [comment]
@shibasarkar damn bro I didn't even assigned you, well give pr for that as we currently need a logo to work with and @BinaryBhakti you can start working on the logo

**Comment by shibasarkar** [comment]
No no i didn't give PR for the logo design issue, I added a service page based on the Explore service button of the hero section

**Comment by Luson045** [comment]
ok then give pr for the logo too @shibasarkar

**Comment by shibasarkar** [comment]
Ok
