### ISSUE TITLE
[FEATURE] Add Lab Test page

### ISSUE THREAD

**Issue by Anwishta** [Luson045/medi-connect#165]
### Description:
This feature request is to add a new Lab Test page to the application, allowing users to browse and book lab tests directly from the platform. The page should provide details about various lab tests, pricing, and an option to schedule an appointment.
### Page Design:

A clean, user-friendly design for the Lab Test page.
Display a list of available lab tests with relevant details such as:
Test name
Short description
Price
A search bar to help users filter specific tests.
Option to sort the lab tests (by price, popularity, etc.).

### Booking Functionality:

Each lab test should have a “Book Now” button.
Users should be able to select a preferred date and time for their test.
A confirmation page after successful booking with appointment details.

**Comment by Luson045** [comment]
currently we dont have that dataset of the hospital. You want to work on this issue? It would require a step by step process

**Comment by Anwishta** [comment]
Yes I want to work on it. At least let me create a basic lab test page, we can improve it step by step.

**Comment by Luson045** [comment]
I'm not saying you should not 😅, but yeah that's how it should be first create the basic page with the current theme and leave the api calls then we can work on backend 👍
