### ISSUE TITLE
Contact Us Text Does Nothing on Click

### ISSUE THREAD

**Issue by MdNadimUddin01** [Luson045/medi-connect#166]
The "Contact Us" section on the website is just text with no functionality. There is no form associated with it.
Expected behavior: Clicking on the "Contact Us" option should open a form. or provide a way for users to contact the team.
can i work on that issues?

**Comment by Luson045** [comment]
nice idea, make a common page and based on the type of service selected by the user.. for example user select contact us, then this page should work for contacting, if user choses to support us this page should show the form form supporting us, if user selects to join us this page should show accordingly and so on for alll the services in the footer, use conditional rendering

**Comment by bj-jiwrajka** [comment]
@Luson045 can you please reassign it to me?

**Comment by MdNadimUddin01** [comment]
i am workin on it.
