### ISSUE TITLE
Create Open-Graph Image and Twitter-Image and sitemap.xml

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#168]
need og-image and twitter-image and sitemap.xml for SEO

**Comment by shibasarkar** [comment]
@Luson045  can i work on this

**Comment by Luson045** [comment]
@shibasarkar okay, but make sure that the files have quality

**Comment by konan625** [comment]
@Luson045 can you assign this to me?

**Comment by Luson045** [comment]
@konan625 issue's taken

**Comment by Luson045** [comment]
@shibasarkar dont make sitemap.xml
