### ISSUE TITLE
Update the hospital data when user data is updated in real timeand vice versa

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#171]
### Discussed in https://github.com/Luson045/medi-connect/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **Luson045** September 30, 2024</sup>
So, I made this feature of appointment booking, where users can book appointment, here are the screenshots
1) User Panel  2)Hospital Panel
<div display="flex">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/561c65b9-86d8-4428-b893-406656226e91">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/a48dee9c-84cc-42dc-8c54-4d314d6f8233">
</div>

This is the user profile page
<img width="400" alt="image" src="https://github.com/user-attachments/assets/42f4c3ef-e1a2-4bfc-bd7e-e36ab69083c6">

now whenever the hospital deletes/ mark as done then it should be updated in the user database too

but it's not working, whenever the appointment is deleted from the hospital database it remains in the user database.

Fix this issue as described above

reference files - Frontend ---> HospitalPanal.jsx, Profile.jsx,   Backend------>index.js in hospital and user files ,   DB Models---> server/models</div>

**Comment by aryanp-86** [comment]
@Luson045 I would like to work on this issue. Please assign it to me.

**Comment by Luson045** [comment]
@aryanp-86 this was an I needed way before. So, if you work on it make sure to do it fast. Complete it by the end of tomorrow

**Comment by aryanp-86** [comment]
@Luson045 Currently the user schema supports three options for status but there is no implementation to use those. Should i also add the mark as done function to fix both delete and complete status in user profile when removed by hospitals.

**Comment by Luson045** [comment]
@aryanp-86 can you check in the deployment.. it is still not working

**Comment by aryanp-86** [comment]
Actually it's a transaction so either it will remove from both or from none. In deployment, it removes only from hospital like old code. I have rechecked again and it works perfectly locally. Will you check once if the production backend server is working on the updated code?

**Comment by Luson045** [comment]
yea, sorry i didn't noticed that 👍
