### ISSUE TITLE
Footer Design Alignment Issue on Mobile Devices

### ISSUE THREAD

**Issue by Mefisto04** [Luson045/medi-connect#180]
### Issue Description:
The current footer design does not align properly on mobile devices, leading to a poor user experience. The elements are either overflowing or misaligned, making it difficult for users to navigate and access the footer content effectively.

**Proposed Solution:**
I would like to contribute to fixing this issue by:
- Reviewing the existing footer component for responsiveness.
- Implementing CSS adjustments to ensure proper alignment and spacing on mobile screens.
- Testing the changes across various mobile devices to ensure compatibility.

**Screenshots:**
![image](https://github.com/user-attachments/assets/1ab0db9c-7e98-430d-adf7-af715ce3cb80)

**Additional Information:**
- Please assign this issue to me so that I can start working on it immediately.
- Also add tag of Hacktoberfest.

**Comment by Luson045** [comment]
it is already fixed
