### ISSUE TITLE
[FEATURE]: Responsive Progress Bar Implementation

### ISSUE THREAD

**Issue by Trevisx07** [Luson045/medi-connect#185]
Implementation of a visually engaging and responsive progress bar for the website.

Details:
The progress bar should be designed to match the current theme and style of the website, ensuring a seamless integration with the existing UI.
It should be visible and functional on both desktop and mobile views, adapting its size and placement for different screen resolutions.

Examples:
![image](https://github.com/user-attachments/assets/3ddb60f6-b577-485a-b555-ef7b83e75f20)

**Comment by NawinKumarSharma** [comment]
@Trevisx07 can you assign me the issue?

**Comment by ar1701** [comment]
I Would like to contribute on this, can you please assign it to me ?

**Comment by Suvendu-UI** [comment]
pls assign me this issue

**Comment by Luson045** [comment]
@NawinKumarSharma YOU CAN GO WITH IT

**Comment by Trevisx07** [comment]
Updates @NawinKumarSharma

**Comment by Luson045** [comment]
@NawinKumarSharma updates?? else you'll be unassigned from this issue
