### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Luson045/medi-connect#186]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by Luson045** [comment]
okay can you dynamically fetch the top contributors from github? it's okay if it's static too @Shariq2003

**Comment by Shariq2003** [comment]
> okay can you dynamically fetch the top contributors from github? it's okay if it's static too @Shariq2003

I am fetching dynamically
