### ISSUE TITLE
IRDA number for uniquely verifying and identifying hospitals so that random people cant register as hospitals 

### ISSUE THREAD

**Issue by keerthana2-005** [Luson045/medi-connect#187]
What if people randomly register for hospitals even if they dont have any inorder to avoid this irda field and verification field can be added

**Comment by keerthana2-005** [comment]
plz assign hacktober fest and gssoc extended labels

**Comment by Luson045** [comment]
@keerthana2-005 currently we are using dummy data for testing i don't think it would be a good decision to validate using irda number. If you have any solution or alternate to that then please share
