### ISSUE TITLE
fix this image for better quality, and resolution

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#189]
<img width="701" alt="image" src="https://github.com/user-attachments/assets/588a073a-0756-43cd-82ae-e0e1afd483c4">
<img width="341" alt="image" src="https://github.com/user-attachments/assets/0e888e14-f56a-46f4-9264-a592cc186e8b">

**Comment by shibasarkar** [comment]
@Luson045 I will improve the image quality
