### ISSUE TITLE
FEAT: Logout Confirmation Popup

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#200]
# Feature Suggestion: Logout Confirmation Popup

Hello @Luson045,

Currently, when the user clicks on the logout button, they are immediately logged out. I would like to suggest adding a confirmation popup to improve the user experience.

## Proposed Change

When the user clicks the logout button, a popup should appear with a message like:

> "Do you really want to log out?"

This popup would have two buttons:
- **Yes**: Proceeds with logging out.
- **No**: Cancels the action and keeps the user logged in.

This will prevent users from accidentally logging out and enhance the overall usability of the site.

### Related Tags
- gssoc-ext
- hactoberfest

Could you please assign this task to me please?

Thank you!

**Comment by tejasbenibagde** [comment]
Thank you for assigning me I'll start working immediately.

**Comment by bj-jiwrajka** [comment]
> Thank you for assigning me I'll start working immediately.

Hey, are you working on it?

**Comment by tejasbenibagde** [comment]
@bj-jiwrajka  Ah yes I did work on it but forgot to create a PR. Thank you for reminding.
