### ISSUE TITLE
[New Feature] Adding a healthcare blog page

### ISSUE THREAD

**Issue by J-B-Mugundh** [Luson045/medi-connect#208]
Feature Description:
The healthcare blog page offers a dedicated space within the platform to share insightful articles, tips, and news on health, wellness, and medical advancements. It provides users with valuable content on various healthcare topics such as preventive care, mental health, fitness, and nutrition.

Benefits:

- Educational Resource: Provides reliable health information and advice, promoting awareness on important healthcare issues.
- User Engagement: Encourages visitors to interact with the platform, improving user retention through valuable content.
- Trust Building: Helps build trust with users by offering expert medical insights and tips, positioning the platform as a credible healthcare resource.
- SEO & Traffic Boost: Regular blog updates can improve search engine rankings and drive more traffic to the platform.
- Community Building: Fosters a sense of community among users through discussions, comments, and sharing of healthcare experiences.Use Case:
- Medical Practitioners: Share expert insights on common health conditions, treatment options, and preventive care tips.

**Comment by J-B-Mugundh** [comment]
@Luson045 @shibasarkar Could you please assign me this issue! I would love to work on this..

**Comment by Luson045** [comment]
@J-B-Mugundh nice idea 📌👍👍

**Comment by Luson045** [comment]
@J-B-Mugundh i need update if you have started working on this, as this is something i was also planning to post as an issue

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh i need update if you have started working on this, as this is something i was also planning to post as an issue

Yeah! I'll prolly finish in 1 or 2 days max!

**Comment by Luson045** [comment]
@J-B-Mugundh bro any updates on this?

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh bro any updates on this?

Yeah bro.. I was facing a small issue on separately blog page.. forgot to work on it.. sorry for taking a long time!

![image](https://github.com/user-attachments/assets/b691fa9e-f127-4916-9790-4cff0d62bcd1)
![image](https://github.com/user-attachments/assets/d94da5c6-34ee-46e9-ad10-06ebbb2c30c0)

**Comment by J-B-Mugundh** [comment]
Need to improve the separate blog page!
