### ISSUE TITLE
Improve Form Validation throughout the website

### ISSUE THREAD

**Issue by satyamohlan** [Luson045/medi-connect#21]
The constraints on form validation throughout the website are not narrow enough, it seems.  Here are the issues I intend to fix.
1. Validate the phone number submitted by the user. 
2.  Add Constraints to the password on the registration page.(Minimum Length, Use of Special Characters, etc)
3.   Add validation to the date of the appointment to ensure appointments can't be made inn the past.

Also, rerouting to login page and registration page for those who are not logged in yet.

**Comment by Luson045** [comment]
Nice  issue 👍, I would like to mark it as level-3 so make sure you're good with node.js and express.js

**Comment by Luson045** [comment]
[IMPORTANT] consider explaining your ideas here and aligning it with others discussion #40

**Comment by Luson045** [comment]
@satyamohlan I'm closing this issue if there's no update by tomorrow noon...

**Comment by Luson045** [comment]
@satyamohlan if you haven't done any major work till now, you can skip this issue. As others have fixed it in different issues.
