### ISSUE TITLE
Refactor backend code into routes, middleware, and controllers for each module

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#210]
I want to refactor the backend code into routes middleware and controller for each module this will increase the modules readability more.
![Screenshot 2024-10-06 150655](https://github.com/user-attachments/assets/f4e626fb-98c3-418d-ad57-8d8f381c421e)

**Comment by 17arindam** [comment]
@Luson045 can i work on this issue?

**Comment by Luson045** [comment]
you need to wait it's better not to change the structure now

**Comment by 17arindam** [comment]
@Luson045 okayy do you have any other backend work currently? I want to contribute to backend too

**Comment by Luson045** [comment]
@17arindam not yet, i'll open issue as soon i find something

**Comment by 17arindam** [comment]
@17arindam okay thanks
