### ISSUE TITLE
I want to change desing of About us page and also want to show some stats showing on about us page with scrolling animation

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#211]
I want to change desing of About us page and also want to show some stats showing on about us page with scrolling animation.

![about2](https://github.com/user-attachments/assets/5e8b8d30-90dc-49c7-a90f-de01fc81d1cb)

https://github.com/user-attachments/assets/56439456-4814-4c55-9a04-d59fb3b6007f

**Comment by Luson045** [comment]
👍👍okay @VinayLodhi1712

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this issue @Luson045

**Comment by VinayLodhi1712** [comment]
Sry, I am already working on this and 50-60% work has done already. So can you plz find any other issue to work
