### ISSUE TITLE
Add hot toast when booking the appointment

### ISSUE THREAD

**Issue by AyushSharma72** [Luson045/medi-connect#217]
![image](https://github.com/user-attachments/assets/874e86dd-7fdc-408b-9edd-0500dadb993c)

i want to add toast notification in place of simple alert when a appointment is booked

please assign this issue to me @Luson045

**Comment by Luson045** [comment]
it is already fixed bro 😅
<img width="960" alt="image" src="https://github.com/user-attachments/assets/c6c9feaa-4f8b-4ed8-be75-e8df6d4b0a64">
if you want to then i can assign you another work related to this??

**Comment by AyushSharma72** [comment]
> it is already fixed bro 😅 <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/131430087/373972776-c6c9feaa-4f8b-4ed8-be75-e8df6d4b0a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDE1MjYsIm5iZiI6MTcyODI0MTIyNiwicGF0aCI6Ii8xMzE0MzAwODcvMzczOTcyNzc2LWM2YzlmZWFhLTRmOGItNGVkOC1iZTc1LWU4ZGY2ZDRiMGE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxOTAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWY1OWI0YTVmMjQ5NWQwYjk5YWIyYzEyOTJlZTNiMzQ5MDRiYWEwNmJjNDg3MTQwMjEzODk2OGZhNTIwYjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-8oSYyP5vPCvK-rk6nyZy7RLKQzcDdcYAyiwh2Gj9OY"> if you want to then i can assign you another work related to this??

Yes tell me ??

**Comment by Luson045** [comment]
@AyushSharma72  just add the logo and title over that pdf and card generated after sucessfull  registration

**Comment by AyushSharma72** [comment]
> @AyushSharma72 just add the logo and title over that pdf and card generated after sucessfull registration

Okay mediplus logo right and what to write in the title ???

**Comment by Luson045** [comment]
@AyushSharma72 Med-Space.. just make a header for the pdf, add logo and name of the project and below add a footer with copyright trademark

**Comment by AyushSharma72** [comment]
hey @Luson045 this issue is not resolved  

![image](https://github.com/user-attachments/assets/4ea03022-acca-4727-9dea-712d979523be)
 

there is an alert message when the user book appointment after login at the hospitals page 

here:
![image](https://github.com/user-attachments/assets/1817fd25-e3a5-4d19-958c-341881968830)


should i raise another issue for this ????

**Comment by AyushSharma72** [comment]
> @AyushSharma72 Med-Space.. just make a header for the pdf, add logo and name of the project and below add a footer with copyright trademark

by the way i resolved this issue check PR   https://github.com/Luson045/medi-connect/pull/257
