### ISSUE TITLE
add loader when the login button is clicked

### ISSUE THREAD

**Issue by AyushSharma72** [Luson045/medi-connect#219]
when the login button is clicked the website do not show any loading while processing the request 

i want to add a loader while the website performs user login request 

![image](https://github.com/user-attachments/assets/61d3349b-99ae-4746-a20f-b0fce4fd3b6d)

please assign this issue to me @Luson045

**Comment by AyushSharma72** [comment]
> when the login button is clicked the website do not show any loading while processing the request
> 
> i want to add a loader while the website performs user login request
> 
> ![image](https://private-user-images.githubusercontent.com/133676532/373938769-61d3349b-99ae-4746-a20f-b0fce4fd3b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTAxMTIsIm5iZiI6MTcyODIwOTgxMiwicGF0aCI6Ii8xMzM2NzY1MzIvMzczOTM4NzY5LTYxZDMzNDliLTk5YWUtNDc0Ni1hMjBmLWIwZmNlNGZkM2I2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMDE2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGYzMjdiYzc1N2NjMWUyMTUyOGQzYzE5MzIwYzRiZjAwYzU2NmMwNWRmY2VhYjYwNGUxYzQ4NzNkZGVlY2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MUKIOhRkEK_46y49jZb6KXpxmG6zrwcSI5qeONBjRUM)

please assign this issue to me @Luson045

**Comment by Luson045** [comment]
@AyushSharma72  okay you can go for it.

**Comment by AyushSharma72** [comment]
> @AyushSharma72 okay you can go for it.

Thanks

**Comment by Luson045** [comment]
@AyushSharma72  I'm closing this issue, as there is already an issue which covers this issue.. please read the pinned issue..
