### ISSUE TITLE
[ENHANCEMENT STYLING] Improve Login for Better Visibility 

### ISSUE THREAD

**Issue by shibasarkar** [Luson045/medi-connect#22]
### Description
We need to add a Forgot password link on the login page along with the Remember me checkbox 
### Actual Behavior
The current Login page is not aligned properly & has not implemented the basic properties required for the login page like forgot and remember me check box
### Expected Behavior
The login page should have the basic properties that improve the login page visibility & functionality 

###Screenshots (if applicable)
Actual
![Screenshot 2024-10-01 182537](https://github.com/user-attachments/assets/ecd4b1e3-e792-4e30-bdea-07a3ecc3fafe)

**Comment by shibasarkar** [comment]
@Luson045 I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by Luson045** [comment]
please take a look at issue #8, there's an issue for frontend of login page, you can work on the backend,comment there and I'll assign you in that issue
