### ISSUE TITLE
Bug Report: Incorrect Social Media Links in Footer Icons

### ISSUE THREAD

**Issue by Shubham0523** [Luson045/medi-connect#221]
Problem: The social media links in the footer icons are not correctly set up, leading to broken or incorrect navigation for users trying to access the respective social platforms.

![Med-Space _ Efficient Healthcare Appointments   Queue Management - Brave 06-10-2024 17_54_13](https://github.com/user-attachments/assets/e8a68f87-5caf-47af-8795-46b074a2dca2)

Proposed Solution: Ensure that each footer icon links to the correct social media page associated with the application. Test all links for accuracy.

Use Cases:
1. Users can seamlessly connect to the app's official social media profiles from the footer section.
2. Improves user trust and brand credibility by avoiding broken links.

**Comment by Luson045** [comment]
@Shubham0523 well currently there are no social media handle for those 😥, I'll add it myself whenever needed.. i cannot just redirect the users to my profiles 😅

**Comment by Shubham0523** [comment]
sure @Luson045
