### ISSUE TITLE
Improving UI of the Register page.✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Luson045/medi-connect#224]
<img width="384" alt="Screenshot 2024-10-06 at 8 47 58 PM" src="https://github.com/user-attachments/assets/18e3fd26-8dbb-442b-bd93-052aefcf8c80">

this is very long register form and i feel it can be improved by making it compact and side by side and it can be improved by added local storage if not already present. @Luson045 please assign me this task.

**Comment by Luson045** [comment]
@T-Rahul-prabhu-38 we're working on multistep form

**Comment by T-Rahul-prabhu-38** [comment]
no i was suggesting , ill make the boxes next to each other so they will fit in the page

**Comment by Luson045** [comment]
yeah yeah i got it, we are actually making multi step form instead of a single form for instant opd, which fix this issue, you can check that in the current PR's
