### ISSUE TITLE
Fixing ESLint warnings 

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#226]
We have tones of ESLint warnings which is not a good code practice. 
Would like work on fixing the ESLint warnings

Problems:
 
<img width="1166" alt="Screenshot 2024-10-06 at 10 23 16 PM" src="https://github.com/user-attachments/assets/eadae7cd-762e-4331-ac4e-76d57d55c3a0">

**Comment by Luson045** [comment]
@lade6501 i'd love to see that gone from my terminal😂
