### ISSUE TITLE
added hover & color change effects to social-icons

### ISSUE THREAD

**Issue by Shekhar-Raj** [Luson045/medi-connect#227]
<h2>I want to add a hover effect to the social icons, so whenever i hover an icon the size of the icon increases and each icon changes its color to basic, Please assign the issue so that i can contribute!</h2>

https://github.com/user-attachments/assets/58473793-cef3-41fc-b752-3a8bf34bca7b

**Comment by Luson045** [comment]
@Shekhar-Raj sorry but i wanna keep it simple...
