### ISSUE TITLE
Implementing mapbox for nearest hospital in vicinity

### ISSUE THREAD

**Issue by Hustler004** [Luson045/medi-connect#228]
I think this can be a very salient feature for this website, fetching the user's location and showing the nearest hospital in its vicinity via the map.
we can use something called maplibre to use free maps, and also if that doesn't work out we can still find some way of showing nearest hospitals, I would really like to go in depth on this implementation.
I don't know if I need to say this but if you consider assigning, assign it to me under hacktoberfest and gssoc tags with level you think is appropriate.
this is the implementation i did on my current project
![image](https://github.com/user-attachments/assets/54ab549d-a2bf-4caa-8637-f309b08776ab)

**Comment by Luson045** [comment]
@Hustler004 Hmm, well you can experiment with that, but please dont go with paid services 😂, also make a new page for this and add the link to that in profile page..

**Comment by Hustler004** [comment]
Okk! Maplibre library is free so let me look into it, although I'll give regular updates but this might take a while so please don't give up on me!

**Comment by Luson045** [comment]
sure sure, that's why i told you to make a new page for this.. so that later it'll be easier to merge @Hustler004

**Comment by Hustler004** [comment]
I've completed the implementation, please check the PR and merge if you like it!

**Comment by Hustler004** [comment]
Can you elaborate more?
@Luson045
