### ISSUE TITLE
Use Regex for FormData Validation

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#231]
#### Description:
The current implementation of form validation does not utilize regular expressions (regex), which limits the flexibility and accuracy of the validation process for certain input fields. Regex allows for more precise control over patterns such as emails, phone numbers, and custom formats that aren't easily handled by basic validation methods.

#### Benefits of Using Regex:
- **Better Control:** Provides fine-grained control over specific patterns (e.g., phone numbers, emails, alphanumeric strings).
- **Customization:** Easily customizable for specific formats or rules.
- **Error Reduction:** Helps prevent incorrect input formats, reducing validation errors.

#### Areas for Improvement:
- Input fields such as [email, phone number, or other custom fields] could benefit from using regex patterns to enforce more strict validation.
- Current validation may be too lenient, allowing for improper input that might cause issues down the line.

### Screenshots
![image](https://github.com/user-attachments/assets/43e13dac-ffc1-40e4-ae66-06dde3b229f0)

**Comment by Rizvi-Faiz** [comment]
@Luson045  Can you please assign this issue to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  work is being done on it

**Comment by Rizvi-Faiz** [comment]
@Luson045  i shared a screen shot and it is not there

**Comment by Rizvi-Faiz** [comment]
@Luson045 i shared a screenshot showing that it is not present so can you assign it to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  k fine, but it should not hinder the user experience, i.e. user must not get annoyed because all his inputs are not being accepted as valid.
