### ISSUE TITLE
Create Customer Care Page

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#232]
#### Description:
We need to design and implement a **Customer Care** page to provide users with essential support resources, contact options, and FAQs. This page should help customers easily find answers to their questions, report issues, and contact the support team for assistance.

#### Features and Requirements:
1. **Contact Information:**
   - Display customer support phone number and email.
   - Provide a live chat option (if applicable) or a link to chat support.
   - Include a contact form for submitting inquiries.

2. **FAQ Section:**
   - Display frequently asked questions with collapsible answers.
   - Categories such as:
     - Account and Billing
     - Orders and Shipping
     - Product Issues
     - Technical Support

3. **Support Ticket System (Optional):**
   - Allow customers to submit support tickets with a description of their issue.
   - Provide status updates on their ticket (e.g., "open," "in progress," "resolved").

4. **Help Articles / Knowledge Base:**
   - Link to helpful articles or troubleshooting guides.
   - Provide instructions on how to perform common tasks (e.g., resetting passwords, returning items).

5. **Design Requirements:**
   - Consistent with the website’s overall design and branding.
   - User-friendly and responsive for all device sizes (mobile, tablet, desktop).
   - Accessible for users with disabilities (ADA compliance).

#### Example Layout:
1. **Header**: Title (Customer Care), brief introduction, contact links.
2. **Main Content**:
   - FAQs (collapsible sections).
   - Contact Form (with input fields like name, email, issue description).
   - Support Ticket System (optional).
3. **Sidebar (Optional)**: Quick links to help articles, phone numbers, and live chat.

#### Acceptance Criteria:
- [ ] The Customer Care page is accessible from the website's main navigation.
- [ ] The page includes a clear and easy-to-use contact form.
- [ ] FAQs are presented in an intuitive collapsible format.
- [ ] The page is responsive and works on various devices.
- [ ] Live chat or other communication options (e.g., phone, email) are clearly visible.
- [ ] Optional: Support ticket system is implemented and functional (if included).

#### Additional Context:
- This page should provide users with a seamless experience to resolve their issues or get help from the support team.
- Ensure that all contact forms have proper validation and user-friendly error messages.

#### References:
- [Link to mockups or wireframes, if available]
- [Any documentation or examples that would assist in the page creation]

#### Checklist:
- [ ] Design and wireframe the Customer Care page.
- [ ] Implement the contact form and FAQ section.
- [ ] Add responsive styling to ensure mobile compatibility.
- [ ] Test the page across different browsers and devices.
- [ ] Optional: Set up support ticket system functionality.

## Screenshots

https://github.com/user-attachments/assets/ac9bdb82-cb98-4e01-b53c-0ab13eef322a

**Comment by Rizvi-Faiz** [comment]
@Luson045  can you asssign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz work is being done on it
