### ISSUE TITLE
"Our Hospitals" Link Not Working in Footer

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#235]
#### Description:
The **"Our Hospitals"** link in the footer section of the website is not functioning as expected. Clicking the link either results in a broken URL or no redirection at all. This issue needs to be resolved to ensure users can access the relevant page easily.

#### Steps to Reproduce:
1. Navigate to any page of the website.
2. Scroll down to the footer section.
3. Click on the "Our Hospitals" link.
4. Observe that the link is either broken or not responding.

#### Expected Behavior:
- Clicking the "Our Hospitals" link should redirect users to the appropriate page that lists or provides information about the hospitals.

#### Actual Behavior:
- The link does not redirect to the correct page or is broken.

#### Potential Cause:
- The link in the footer might be outdated or incorrectly formatted.
- The URL of the "Our Hospitals" page might have changed without updating the footer link.

#### Suggested Solution:
- Verify the correct URL for the "Our Hospitals" page.
- Update the footer link to point to the correct and functional URL.
- Test the link across multiple browsers and devices to ensure it works as expected.

#### Acceptance Criteria:
- [ ] The "Our Hospitals" link in the footer redirects to the correct page.
- [ ] The link works properly across different devices (mobile, tablet, desktop).
- [ ] The footer design remains consistent after the link update.
- [ ] Test to ensure the link is functional on different browsers (Chrome, Firefox, Safari, etc.).

#### Additional Context:
- Ensure that the page being linked to is live and accessible.
- Consider adding a unit test or browser test to ensure the footer links are working in future updates.

#### References:
- [Provide the current URL or intended destination for the "Our Hospitals" page, if available.]

#### Checklist:
- [ ] Identify the correct URL for the "Our Hospitals" page.
- [ ] Update the link in the footer.
- [ ] Test the updated link across multiple browsers and devices.
- [ ] Ensure the footer remains responsive after the update.

### Videos

https://github.com/user-attachments/assets/5ff6248b-8d00-4ced-b1b0-93415fd954e6

**Comment by Rizvi-Faiz** [comment]
@Luson045 can you assign this issue to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  none of those links are working, once the pages are ready we will add those
