### ISSUE TITLE
Create Terms and Conditions Page

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#236]
#### Description:
We need to design and implement a **Terms and Conditions** page to outline the legal agreements between the company and the users of the website/application. This page will provide clear and concise information about the rules, rights, and responsibilities of both parties.

#### Key Sections to Include:

1. **Introduction:**
   - A brief overview of the purpose of the Terms and Conditions.
   - State the effective date and any updates made to the terms.

2. **User Obligations:**
   - List the user responsibilities (e.g., providing accurate information, complying with applicable laws).
   - Restrictions on the use of the service (e.g., no misuse, illegal activities, or copyright violations).

3. **Intellectual Property:**
   - Clarify ownership of the website's content (e.g., text, images, logos) and any intellectual property rights.
   - State any limitations on user use of intellectual property.

4. **Limitation of Liability:**
   - Limit the liability of the company for certain damages or losses.
   - State that the company is not liable for third-party content or issues outside of its control.

5. **Termination:**
   - Define the conditions under which either party can terminate the agreement.
   - Outline the consequences of terminating access to the website or service.

6. **Governing Law:**
   - Specify which country's laws govern the Terms and Conditions.
   - Provide details about jurisdiction in the case of disputes.

7. **Changes to the Terms:**
   - Include a section that allows the company to update or change the Terms and Conditions at any time.
   - Notify users about how they will be informed of changes (e.g., via email or website notification).

8. **Contact Information:**
   - Provide a way for users to contact the company with questions about the Terms and Conditions.

#### Design Requirements:
- The page should be simple and easy to read, with clear section headings.
- Ensure the page follows the same design style as the rest of the website.
- Include anchor links to allow users to quickly navigate to different sections of the Terms.
- Ensure that the page is responsive and works well on mobile, tablet, and desktop devices.

#### Example Layout:
1. **Header:** Title (Terms and Conditions) with the effective date.
2. **Main Content:** Break down the terms into sections such as user obligations, intellectual property, etc.
3. **Footer:** Contact information and a disclaimer about updates.

#### Acceptance Criteria:
- [ ] The "Terms and Conditions" page is accessible from the website’s footer or a relevant location.
- [ ] The page includes all the necessary sections and legal terms.
- [ ] The page is responsive and works across different devices.
- [ ] The language used in the document is clear, concise, and legally compliant.

#### Checklist:
- [ ] Draft the content for each section of the Terms and Conditions.
- [ ] Design and implement the page with clear headings and navigation.
- [ ] Review the terms with legal counsel to ensure compliance.
- [ ] Test the page across multiple browsers and devices to ensure responsiveness.

**Comment by Rizvi-Faiz** [comment]
@luson can you assign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  okay

**Comment by Rizvi-Faiz** [comment]
@Luson045  please assign it to me

**Comment by Rizvi-Faiz** [comment]
@Luson045  creating a whole new page with styling is level1 ?
can you at least give level2 .

**Comment by Luson045** [comment]
Level2 is for very much of visually appealing pages where a lot of designing is needed 
Or level2 is for something that is very important at the moment
Even gpt can generate me a whole terms and conditions page.

Anyway, If you want level2 then give PR by tonight. I'll give level2 👍🏻

**Comment by Rizvi-Faiz** [comment]
ok @Luson045 sir 
Thank you for consideration.
