### ISSUE TITLE
Add Correct Data in the List of Hospitals

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#237]
#### Description:
The **List of Hospitals** page needs to be updated with accurate and verified information. The current data may be incomplete, outdated, or incorrect. This issue involves reviewing, verifying, and updating the hospital details to ensure they are correct and up-to-date.

#### Data to be Updated:
1. **Hospital Name:**
   - Ensure that the hospital names are spelled correctly and formatted consistently.

2. **Address:**
   - Verify that the full address, including street, city, and postal code, is accurate.
   - Ensure the address format follows local conventions.

3. **Contact Information:**
   - Update phone numbers, email addresses, and website links if they have changed.
   - Ensure that all contact details are functional and correctly formatted.

4. **Specialties or Services Offered:**
   - Verify the services or specialties listed for each hospital.
   - Add any missing information about services or facilities if necessary.

5. **Operating Hours:**
   - Ensure that the operating hours are current and consistent across all hospitals.
   - Update the hours for holidays or special conditions (if applicable).

6. **Map Integration (Optional):**
   - Ensure the embedded map or link to the hospital’s location is working properly.
   - Verify that the pin on the map corresponds to the correct address.

#### Steps to Complete:
1. **Data Collection:**
   - Gather the correct information for each hospital (e.g., from official hospital websites or government directories).
   - Cross-check the data with reliable sources.

2. **Data Update:**
   - Update the hospital names, addresses, contact information, and other relevant fields in the database or content management system (CMS).
   - Ensure consistent formatting across all entries.

3. **Testing and Verification:**
   - Test the updated hospital links and contact details to ensure everything is working.
   - Review the page layout to ensure the information is displayed properly on all devices.

#### Acceptance Criteria:
- [ ] All hospital names are correct and formatted consistently.
- [ ] The address and contact information for each hospital is verified and up-to-date.
- [ ] The services and specialties listed are accurate and complete.
- [ ] Optional: The map or location link works and points to the correct address.
- [ ] The page is responsive across different devices (mobile, tablet, desktop).

#### Checklist:
- [ ] Collect the correct information for each hospital.
- [ ] Update the hospital data in the database or CMS.
- [ ] Verify and test the contact details, addresses, and services.
- [ ] Ensure the map integration or links are working properly.
- [ ] Test the page across multiple browsers and devices.

### Screenshots
![image](https://github.com/user-attachments/assets/00bbf3ea-5d16-4600-a8b9-26bdbb4aa7e3)

**Comment by Rizvi-Faiz** [comment]
@Luson045  assign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz you are generating so many issues, since the modification is being done at an exponential rate, any outdated PR won't be entertained. Make sure to note this..

Give me a confirmation if you're okay with that, if some issues are not completed soon, it'll be assigned to someone else.

**Comment by Rizvi-Faiz** [comment]
No @Luson045  i can do them please assign me the issues

**Comment by Luson045** [comment]
Okay complete within 2 days.. any delay will cause in assigning other contributors
