### ISSUE TITLE
Add Filter in Search Bar to Filter Hospitals

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#238]
#### Description:
We need to enhance the search functionality on the **List of Hospitals** page by adding filter options. This feature will allow users to filter hospitals based on specific criteria such as location, specialty, services, or availability. The goal is to make it easier for users to find hospitals that match their needs.

#### Features and Requirements:

1. **Filter Criteria:**
   - **Location:**
     - Users should be able to filter hospitals by city, state, or postal code.
   - **Specialties:**
     - Users can filter hospitals based on specialties (e.g., cardiology, neurology, pediatrics, etc.).
   - **Services Offered:**
     - Allow filtering based on specific services (e.g., emergency care, surgery, outpatient services).
   - **Availability:**
     - Filter hospitals based on availability (e.g., open 24/7, emergency services available).

2. **Search and Filter Interaction:**
   - The search bar should allow free text input, and filters should be applied either via dropdown menus or checkboxes.
   - When a filter is applied, the hospital list should dynamically update to show only the relevant hospitals.
   - The search bar should still function as a keyword search (e.g., typing "Cardiology" should show all hospitals with cardiology services).

3. **UI/UX Considerations:**
   - The filters should be easy to access and user-friendly, possibly displayed as dropdowns or checkboxes beside or below the search bar.
   - Make sure the filter options are responsive and work well on both mobile and desktop devices.
   - Add a "clear filters" button to reset the search and filters.

4. **Backend Integration:**
   - Ensure that the filtering mechanism is properly integrated with the existing hospital database.
   - Optimize queries to ensure fast response times when filters are applied.

5. **Testing:**
   - Test the filter functionality with various combinations of search terms and filters to ensure accurate results.
   - Verify that the filters work across different devices (mobile, tablet, desktop).

#### Example Layout:
1. **Search Bar**: 
   - Standard text input for keyword searches.
2. **Filter Options**:
   - Dropdown or checkbox options for location, specialties, services, and availability.
3. **Results Section**:
   - Display the filtered list of hospitals that match the search criteria.

#### Acceptance Criteria:
- [ ] The search bar allows users to filter hospitals by location, specialties, services, and availability.
- [ ] The list of hospitals updates dynamically based on the applied filters.
- [ ] The "clear filters" button resets all filters and shows the full list of hospitals.
- [ ] The filtering functionality is responsive and works across mobile, tablet, and desktop devices.
- [ ] The search and filter mechanism is optimized for fast performance.

#### Additional Context:
- Consider adding filter analytics to track which filters users are applying the most.
- The filter design should be intuitive, keeping user experience in mind, especially for users on mobile devices.

#### Checklist:
- [ ] Design and implement the filter options.
- [ ] Integrate filters with the backend database.
- [ ] Test the filters with various input combinations.
- [ ] Ensure responsiveness and cross-browser compatibility.
- [ ] Add a "clear filters" button for user convenience.

### Screenshots
![image](https://github.com/user-attachments/assets/ad43f5b2-109c-4a56-8710-beec96725502)

**Comment by Rizvi-Faiz** [comment]
@Luson045 assign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  updates?

**Comment by Rizvi-Faiz** [comment]
Can I complete by tomorrow night 
I have my exams .

**Comment by Luson045** [comment]
sure @Rizvi-Faiz
