### ISSUE TITLE
Add "Our Services" to Navbar

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#239]
#### Description:
We need to add a new **"Our Services"** link to the website's navbar for easier access to the services page. This will help users quickly navigate to the services offered by the organization. The new link should be integrated smoothly into the existing navbar layout.

#### Features and Requirements:

1. **Navbar Update:**
   - Add an **"Our Services"** link in the navbar.
   - Position the link appropriately based on the existing navbar structure (e.g., after "About Us" or before "Contact Us").
   
2. **Link Target:**
   - The "Our Services" link should redirect to the services page (ensure the correct URL is used).
   - If the services page does not yet exist, ensure that the correct placeholder or coming soon page is linked temporarily.

3. **Design Considerations:**
   - Ensure that the design of the navbar remains consistent after the new link is added.
   - Maintain the responsive design of the navbar so that it works across all devices (mobile, tablet, desktop).
   - The new link should be clearly visible and fit the style of the rest of the navbar items.
   - Ensure proper spacing and alignment of the link, especially in the responsive view (mobile dropdowns, etc.).

4. **Testing:**
   - Test the updated navbar on different screen sizes (mobile, tablet, desktop) to ensure it’s responsive.
   - Ensure the "Our Services" link works correctly and navigates to the intended page.
   - Test for cross-browser compatibility (Chrome, Firefox, Safari, Edge).

#### Acceptance Criteria:
- [ ] The "Our Services" link is added to the navbar and appears in the correct position.
- [ ] The link directs users to the services page.
- [ ] The navbar remains responsive and functional on all devices.
- [ ] Cross-browser compatibility is maintained.
- [ ] The design of the navbar remains consistent and aligned after the addition.

#### Additional Context:
- Ensure that the services page exists and is properly linked from the navbar. If the services page is under construction, a "Coming Soon" page or section can be linked temporarily.

#### Checklist:
- [ ] Add the "Our Services" link to the navbar.
- [ ] Ensure the link targets the correct services page.
- [ ] Test the responsiveness and appearance on all devices.
- [ ] Test cross-browser compatibility.

### Screenshots
![image](https://github.com/user-attachments/assets/414c2582-5821-41ee-8813-cd4669684a4e)

**Comment by Rizvi-Faiz** [comment]
@Luson045  can you assign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz  ok
