### ISSUE TITLE
create FOOTER

### ISSUE THREAD

**Issue by Ketanop321** [Luson045/medi-connect#24]
there is no footer in your website

**Comment by Luson045** [comment]
yes I was about to create that issue, i would assign you
take reference from this site

and please try to give all your issues in a single issue
https://learnstocks.netlify.app/
<img width="947" alt="image" src="https://github.com/user-attachments/assets/09f06254-fd9f-41fb-98c0-3db47c36f306">

**Comment by Luson045** [comment]
@Ketanop321 any updates?

**Comment by Ketanop321** [comment]
> @Ketanop321 any updates?

It will be merged before midnight🙏🙏🙏
