### ISSUE TITLE
Removing the "read more" phrase

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#240]
## Issue
Removing the " read more " phrase from the required phrases as it has no more content and is giving users wrong information
And as there is no more information is is just some text . 
### Screenshots
![image](https://github.com/user-attachments/assets/13d662f3-f5e0-4667-85e0-39a82070d544)

**Comment by Rizvi-Faiz** [comment]
@Luson045 Can you assign this to me.

**Comment by Luson045** [comment]
@Rizvi-Faiz okay
