### ISSUE TITLE
Appointment Status Update Feature

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#241]
We need to implement a feature that allows hospital staff to approve or reject patient appointments. This feature will update the status of appointments accordingly in the database and provide feedback to the user interface.

![Screenshot 2024-10-07 055346](https://github.com/user-attachments/assets/e0c2835f-6640-40ce-b971-a46103229465)

**Comment by 17arindam** [comment]
@Luson045 can you assign me this issue?

**Comment by Luson045** [comment]
It's already there, the delete button in OPD panel is for this purpose only
