### ISSUE TITLE
Quick fix

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#245]
Fix this

![Screenshot_2024-10-07-11-47-31-59_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/25bfc55a-a91a-4d78-a85e-ee02709c0e16)

**Comment by lade6501** [comment]
Is it in mobile view ?

**Comment by Trevisx07** [comment]
@lade6501 Yes!...Will you work on it?

**Comment by varma-101** [comment]
I'd like to work on this @Luson045

**Comment by varma-101** [comment]
bro i've finished work.please add level label also.and take a look at this
for small devices such as iphone se
![image](https://github.com/user-attachments/assets/a9936802-43ac-4307-8c43-8915dd03661f)

for large and medium devices such as samsung etc
![image](https://github.com/user-attachments/assets/4508806a-aeb2-44d8-b114-c7165aa48f6d)

**Comment by varma-101** [comment]
if you add the level label, i will make pr.

**Comment by Luson045** [comment]
@varma-101 😂😂, damn as if i dont add labels on PR, issue PR doesn't count in gssoc and hacktoberfest anyway for your sake i'm adding it here

**Comment by Luson045** [comment]
btw @varma-101 you weren't even assigned this 🤔, I'm getting sick of people working on other's issues and giving sudden PR, asked the gssoc admins and they told to report it the next time, behave yourself yaar!!

**Comment by varma-101** [comment]
![image](https://github.com/user-attachments/assets/077a49e2-fffa-4e95-ac04-0b2480195f2f)
he assigned me i'm doing without informing.

**Comment by varma-101** [comment]
explain this @Luson045 ?
