### ISSUE TITLE
Fix the deprecated packages

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#246]
As a lot of people are working on a lot of issues many deprecated modules have been used recently.. 

Your task is to replace as many deprecated packages as possible making sure that everything is functioning as it is in the production and no feature is changed.

For this issue there's no first come first serve!!

Will be assigned based on expertise and work history.

**Comment by aryanp-86** [comment]
I would like to work on this.

**Comment by lade6501** [comment]
would like to work on above.

**Comment by Luson045** [comment]
@aryanp-86 you can go for it

**Comment by aryanp-86** [comment]
Okay👍

**Comment by aryanp-86** [comment]
@Luson045 Hi, actually I was still working on the deprecated packages.Almost finished
