### ISSUE TITLE
Reduce the size of header.

### ISSUE THREAD

**Issue by vijaychandra1910** [Luson045/medi-connect#25]
![Screenshot 2024-10-01 201542](https://github.com/user-attachments/assets/5afa412d-cb82-472f-983f-29a73e03ebcd)
Here the size of logo and header is large also the size of font are large that reduce user attraction.
To attract user reduce header size and also use logo instead of full name

**Comment by xauravww** [comment]
Hi,
I'd like to work on this issue. Could you please assign it to me?
Thanks!

**Comment by Luson045** [comment]
issue #14 covers this
