### ISSUE TITLE
Add Monitoring with Grafana and Prometheus

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#251]
## Summary
I’d like to set up Grafana and Prometheus to improve our monitoring.

## Benefits
- **Better Visibility**: We’ll get clear insights into how our system is performing.
- **Catch Issues Early**: This setup will help us spot problems before they become major issues, reducing downtime.
- **Informed Decisions**: With access to real data, we can make smarter choices about our system.
- **Custom Dashboards**: We can create dashboards that show the information that matters most to us.
- **Optimize Resources**: We’ll be able to see where we might be wasting resources and make adjustments.

Overall, adding these tools will help us keep our system running smoothly. I’d love to hear your thoughts!

**Comment by Luson045** [comment]
that's a great idea @tejasbenibagde , there are already a lot of redundant resources in the repo, would love to see it in action

**Comment by tejasbenibagde** [comment]
Thank you for assigning me. I'll start working as soon as possible.
