### ISSUE TITLE
Mobile UI Issue on Book Appointment Page

### ISSUE THREAD

**Issue by ShaikHafiza** [Luson045/medi-connect#255]
When accessing the (https://med-space.vercel.app/hospitals) on mobile devices and clicking on the "Book Appointment" button, the alignment, padding, and margins are not properly set. Additionally, the "User" heading is not clearly visible.

![WhatsApp Image 2024-10-07 at 14 55 23_064da39a](https://github.com/user-attachments/assets/b1c210fe-9dc9-4495-b0e4-c39de5a64207)

**Comment by Luson045** [comment]
@ShaikHafiza okay you can work on it but please stay in sync with the latest changes in repo

**Comment by ShaikHafiza** [comment]
Ok Thanks @Luson045
