### ISSUE TITLE
[BUG] Preset For Github Issues

### ISSUE THREAD

**Issue by 4F24L** [Luson045/medi-connect#259]
## #Preset for Github Issues
- I can make a preset for github issues
- Two form can be created.
- BUG and Feature form

![image](https://github.com/user-attachments/assets/fe6ad391-d2ba-43c9-bc7c-14776e0cf2ff)
##

### #Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by Luson045** [comment]
okay

**Comment by 4F24L** [comment]
Please update the label of this issue to level2. 

You updated the PR, but this issue is left by chance.

**Comment by Luson045** [comment]
@4F24L it doesn't affect your score
