### ISSUE TITLE
Login section overlap

### ISSUE THREAD

**Issue by vijaychandra1910** [Luson045/medi-connect#26]
![Screenshot 2024-10-01 202547](https://github.com/user-attachments/assets/8980fad9-699a-4161-af3e-b793fbc7a0ab)
This login password are overlap to each other give it some margin for spacing.

**Comment by xauravww** [comment]
Hi,
I'd like to work on this issue. Could you please assign it to me?
Thanks!

**Comment by vijaychandra1910** [comment]
Sure!
