### ISSUE TITLE
[Bug]: Navbar does not reset scroll position when navigating between pages

### ISSUE THREAD

**Issue by bj-jiwrajka** [Luson045/medi-connect#263]
**Description:** When navigating between pages using the navbar, the scroll position from the previous page is retained. For example, if a user scrolls to the bottom of one page and then navigates to a different page, the new page also opens at the bottom, rather than resetting to the top.

**Expected Behavior:** When navigating to a new page, the scroll position should reset to the top of the page.

**Actual Behavior:** The new page retains the scroll position from the previous page.

**Possible Fix:** Ensure the scroll position is reset to the top when navigating to a new page, possibly by adding a window.scrollTo(0, 0) in the page navigation logic.

**Comment by bj-jiwrajka** [comment]
@Luson045 please assign it to me

**Comment by Luson045** [comment]
@bj-jiwrajka okay

**Comment by bj-jiwrajka** [comment]
@Luson045 this bug needs to be resolved. Please let me do it. If you're facing any difficulties to understand, let me know
