### ISSUE TITLE
[Bug]: Email field does not validate format, allows invalid entries

### ISSUE THREAD

**Issue by bj-jiwrajka** [Luson045/medi-connect#264]
**Description:** The email input field currently does not validate the email format. Users can enter invalid email formats (e.g., missing @, no domain) such as "abc", and the form proceeds to the next section without showing any warning or error.

**Steps to Reproduce:** 

- Go to the form that contains the email field.
- Enter an invalid email (e.g., "abc" without an @ symbol).
- Submit the form or proceed to the next section.
- Observe that no validation error is shown, and the form moves to the next section.

**Expected Behavior:** The email input field should validate the format of the entered email. If the format is invalid (e.g., missing @, missing domain), a warning or error message should be displayed, and the user should not be allowed to proceed until a valid email is entered.

**Actual Behavior:** Invalid email formats (e.g., "abc") are accepted without any validation, and the user is allowed to proceed to the next section of the form.

**Screenshots:**
![image](https://github.com/user-attachments/assets/c21a68a0-10a3-43d2-8073-3a7d11967ee2)
![image](https://github.com/user-attachments/assets/29a775fa-b282-493c-8949-779a94d357b2)

**Possible Fix:** Add email format validation using a regex pattern (e.g., HTML5 email input type or a custom regex) to ensure the entered email is valid. Provide appropriate error messages for invalid entries.

**Comment by bj-jiwrajka** [comment]
@Luson045 please assign this issue to me :)

**Comment by bj-jiwrajka** [comment]
@Luson045 would you like me to work on it?

**Comment by ROKUMATE** [comment]
@bj-jiwrajka Complete it by the end of today

**Comment by ROKUMATE** [comment]
@bj-jiwrajka If possible check similar regex patter for phone no. Also that it should accept only 10 digit phone no. Also if u can add a strong password feature then it will be good.

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka If possible check similar regex patter for phone no. Also that it should accept only 10 digit phone no. Also if u can add a strong password feature then it will be good.

I haved added eegex pattern for email and phone number. I would like to make a separate PR for for strong password feature since it is a different issue.

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka Dont make a separate issue ... do in this issue itself i will label it level 2 ... As this issue is very small to give a label

okay

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka Dont make a separate issue ... do in this issue itself i will label it level 2 ... As this issue is very small to give a label



> @bj-jiwrajka Dont make a separate issue ... do in this issue itself i will label it level 2 ... As this issue is very small to give a label

you may close this issue now
