### ISSUE TITLE
[feat]: Auto-fill state and city based on pin code in the registration form

### ISSUE THREAD

**Issue by bj-jiwrajka** [Luson045/medi-connect#266]
**Description:** To streamline the registration process and improve uniformity in the database, the form should collect the pin code first and automatically fetch the corresponding state and city. This will also improve accuracy and enhance the user experience by reducing manual input.

**Feature Suggestion:**

- Add the pin code field before state and city fields.
- Once the pin code is entered, automatically fetch and display the corresponding state and city fields.

**Benefits:**

- Enhances user experience by reducing the need for manual input of state and city.
- Improves data accuracy by ensuring that the state and city match the pin code.
- Improves uniformity in the database.

**Screenshots:**

![image](https://github.com/user-attachments/assets/16e9b473-da2e-44e8-8fdf-57a152051574)

@Luson045 please assign it to me

**Comment by Luson045** [comment]
not needed
