### ISSUE TITLE
update Git Ignore

### ISSUE THREAD

**Issue by Rizvi-Faiz** [Luson045/medi-connect#268]
I have noticed that the git ignore file does 'nt has the required files like node_modules and docker related things
ScreenShot:
![image](https://github.com/user-attachments/assets/9d8b09fb-8a00-4cfe-9ed3-f11c4046c61c)
@Luson045  assign this to me

**Comment by Luson045** [comment]
@Rizvi-Faiz OKAY

**Comment by lade6501** [comment]
This issue is addressed in #274
