### ISSUE TITLE
Adding sign in with google option in login page

### ISSUE THREAD

**Issue by reshamsai150** [Luson045/medi-connect#27]
We need to integrate a “Sign in with Google” option into our login page to enhance user experience and security.

**Comment by Luson045** [comment]
Great, consider using OAuth 👍

**Comment by Luson045** [comment]
[IMPORTANT] consider explaining your ideas here and aligning it with others discussion #40

**Comment by ar1701** [comment]
I Would like to contribute on this, can you please assign it to me ?

**Comment by Abhi0049k** [comment]
@Luson045 can you assign this issue to me?

**Comment by Luson045** [comment]
@ar1701 you can go with it, but I need some update on this by day after tomorrow 👍🏻

@Abhi0049k sorry it's first come first serve, you can wait, if there's no response on this issue again then I'll assign you.

**Comment by Luson045** [comment]
@ar1701  updates...

**Comment by ar1701** [comment]
it is in progress...will completed by tonight

**Comment by ar1701** [comment]
I am getting an issue on running it in my local pc

**Comment by Luson045** [comment]
okay try to solve it...

**Comment by 17arindam** [comment]
@Luson045 is this issue solved or can i work on it?

**Comment by Luson045** [comment]
@17arindam it's open but @ar1701 is working on it, and it's not a priority issue so i don't mind late submission

**Comment by Luson045** [comment]
@ar1701 if no response comes by the end of tomorrow then you can work with this

**Comment by 17arindam** [comment]
@Luson045  Okay thank youu

**Comment by Abhi0049k** [comment]
@Luson045 can you assign me this issue?

**Comment by 17arindam** [comment]
@Luson045 is there any update regarding this issue can you assign me this

**Comment by 17arindam** [comment]
@Luson045 thanks

**Comment by Satyams-23** [comment]
This PR solves the issue of adding a "Sign in with Google" option to the login page for an enhanced user experience and security.

- Implemented Google OAuth 2.0 using `passport-google-oauth20`.
- Added routes for Google authentication and session management.
- Updated the frontend login page with a Google Sign-In button.

#344  has solved the issues of adding "Sign in with Google" option in the login page as mentioned in #27.

Closes #27
