### ISSUE TITLE
UI update in navbar

### ISSUE THREAD

**Issue by amitroy-thedev** [Luson045/medi-connect#272]
Currently there is no hover or active state applied to navbar item and the login and register buttons also looks inconsistent, I want to redesign the navbar ui as below

![image](https://github.com/user-attachments/assets/15a1e70c-d260-4db5-8c9d-6b355d727fd8)
@Luson045 assign me this issue...

**Comment by amitroy-thedev** [comment]
also label is as gssoc-ext, gssoc and hacktoberfest

**Comment by Luson045** [comment]
not needed
