### ISSUE TITLE
Proposal : Add github pre-commit hool to prevent eslint warnings

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#274]
In current scenario devs are able to commit their changes even if `eslint` warnings are present.
By adding a pre-commit hook for `eslint` devs will only be able to commit there changes when all `eslint` warnings are addressed.

**Comment by Luson045** [comment]
@lade6501  yeah sure, that'd be nice.. 👍

**Comment by lade6501** [comment]
Yes
