### ISSUE TITLE
Showing Not-Found page when user entered wrong url

### ISSUE THREAD

**Issue by G-Rajashekar** [Luson045/medi-connect#276]
When user entered wrong url it is not showing not-found page
![Screenshot (442)](https://github.com/user-attachments/assets/6ad5536a-7b03-40e9-a3c4-30108cb6398b)

If user entered wrong url it will be good display the not-found page

**Comment by G-Rajashekar** [comment]
Assign this issue to me

**Comment by Luson045** [comment]
yeah sure you can work on a 404 page @G-Rajashekar
