### ISSUE TITLE
Adding validation in OPD Registration page

### ISSUE THREAD

**Issue by Pushpa472** [Luson045/medi-connect#277]
@Luson045 we can add more validation in OPD registration page like email id should be example@gamil.com, contact no should enter 10 if user not enter 10 digit it will show enter validate number, address should not exceed more than 30 or50 and pincode should be 6 digit..
![image](https://github.com/user-attachments/assets/6bc95cc5-3332-4bea-968b-f28149b20f62)

**Comment by Luson045** [comment]
not needed
