### ISSUE TITLE
proper alignment of div

### ISSUE THREAD

**Issue by reshamsai150** [Luson045/medi-connect#28]
![image](https://github.com/user-attachments/assets/83aded4b-45cc-435e-ba1b-7af1c963ad0b)
in this section alignment of div is improper

**Comment by Luson045** [comment]
okay will assign this issue to you, but please confirm if you can add some images in the hero section, like these ?
![image](https://github.com/user-attachments/assets/c7462979-05b1-4a2a-9d49-cf24d0b7a7de)
![image](https://github.com/user-attachments/assets/b7ac4dec-51c5-4337-9297-5f6ec5bc394c)

**Comment by Luson045** [comment]
@CodexRaunak  if the author is not interested.

**Comment by CodexRaunak** [comment]
yeah sure!

**Comment by reshamsai150** [comment]
I will add images also @Luson045

**Comment by Luson045** [comment]
Okay @reshamsai150 

Sorry @CodexRaunak you can explore other issues, there are a lot
