### ISSUE TITLE
save the DORAEMON game

### ISSUE THREAD

**Issue by Ketanop321** [Luson045/medi-connect#281]
![image](https://github.com/user-attachments/assets/0d6fd236-87cc-41d6-858b-b91b972be5c8)

**Comment by Luson045** [comment]
@Ketanop321 don't spam

**Comment by Ketanop321** [comment]
> @Ketanop321 don't spam

ssorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyyy🙏🙏🙏🙏
that was really a mistakeeeeeeeeeeeeeeeeeeeeeeee🙏🙏🙏🙏🙏🙏🙏🥲🥲🥲😭😭😭😭😭

**Comment by Luson045** [comment]
If I wasn't a Pokemon fan I would've reported for sure 😂...
