### ISSUE TITLE
Bug : Giving an error while registering 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#284]
I don't know if I am wrongly filling the form or its a bug because register functionality have some bug like this.

![pincode require error](https://github.com/user-attachments/assets/812dc810-55fd-4826-8640-8fac4a18518b)

**Comment by Luson045** [comment]
@VinayLodhi1712 maybe the guy who worked on it might have changed the data being sent to the backend 🤦‍♂️, would you like to work on it?

**Comment by Luson045** [comment]
@VinayLodhi1712 i was able to register successfully, can you check if your pin is correct, or maybe it's some issue with pin validation

**Comment by VinayLodhi1712** [comment]
yeah i would love to work on it. But can you just tell me the database url i have to use mine..? and I need some time to see what are the things mainly creating problem?

**Comment by Luson045** [comment]
Well you can make a new mongodb collection and connect to that, the models are already there in the backend. So all you need to do is create a new mongodb database on mongodb and get the connection uri for testing.

**Comment by Akshithsaai** [comment]
@Luson045 I have tried to register a hospital to work on a issue. But I couldn't register due to pincode error.

I have used dummy details and ensured the pincode is correct. 

Please Check out this:
![IMG_20241008_183123.jpg](https://github.com/user-attachments/assets/1d38d008-e49c-48ed-a68e-f4216ee4770d)

**Comment by lade6501** [comment]
Hi @VinayLodhi1712  could you share network response ss.

**Comment by Luson045** [comment]
@lade6501 i think we need to re work on the pincode validation, it is not working sometimes 🤔

**Comment by Luson045** [comment]
@Akshithsaai share the screenshot of response in the network section

**Comment by lade6501** [comment]
> @lade6501 i think we need to re work on the pincode validation, it is not working sometimes 🤔

Yeah I tested few scenarios, in some it's working and in some it's not, also noticed that DOB field is causing error due to `Date` type.

**Comment by lade6501** [comment]
Will start working soon on it just finishing pre-commit issue.

**Comment by Akshithsaai** [comment]
> @Luson045 I have tried to register a hospital to work on a issue. But I couldn't register due to pincode error.
> 
> I have used dummy details and ensured the pincode is correct. 
> 
> Please Check out this:
> ![IMG_20241008_183123.jpg](https://github.com/user-attachments/assets/1d38d008-e49c-48ed-a68e-f4216ee4770d)
> 
> 

@Luson045 I have shared the network screenshot here

**Comment by Akshithsaai** [comment]
> @Akshithsaai share the screenshot of response in the network section

![image](https://github.com/user-attachments/assets/f99eb050-4f7c-4dec-9ff7-15681e770e02)
@Luson045

**Comment by Luson045** [comment]
@Akshithsaai validation issue i guess

**Comment by Akshithsaai** [comment]
> @Akshithsaai validation issue i guess

Yeah I think so too @Luson045 
@lade6501 mentioned about it. He said he is working on it. May be that should fix.

**Comment by VinayLodhi1712** [comment]
so can you guys tell me i have to work on this issue or not

**Comment by lade6501** [comment]
Hey @VinayLodhi1712  i checked pincode is working fine, geocode api is not working an giving empty array 
`const results = await geocoder.geocode(address.postalCode + " India");`  but same code is working fine in `../hospital/index.js` could you check for same.

**Comment by lade6501** [comment]
It looks like it working fine I tried adding few hospitals and got success. User DOB issue is still there.

**Comment by lade6501** [comment]
Hi @Luson045 pincode is working fine, due to cache it's giving error some times, but I created user and hospitals multiple time, it worked fine.

**Comment by Luson045** [comment]
@lade6501 okay then it's fine then

**Comment by Luson045** [comment]
@VinayLodhi1712 sorry to unassign you.. You can work on this  issue #366
