### ISSUE TITLE
[Feat] Modal to confirm Logout 

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add a confirmation modal when user click on logout as currently user can logout due to misclick too . A modal will prompt user do they really want to logout this will enhance user experience 

### Use Case

this can be used to avoid logging out due to misclick 

### Benefits

this will help them to avoid logging out due to misclick and again typing there credentials 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 17arindam** [comment]
@Luson045 should i work on this?

**Comment by Luson045** [comment]
@17arindam work is being done on tht
