### ISSUE TITLE
dark mode toggle 

### ISSUE THREAD

**Issue by reshamsai150** [Luson045/medi-connect#29]
adding the dark mode and light mode toggle to enhance the user experience

**Comment by Luson045** [comment]
Would be great 👍, change the themes accordingly

**Comment by Luson045** [comment]
Any updates??

**Comment by Luson045** [comment]
@Abhi0049k assigned 👍🏻, but I need this in 2 days

**Comment by Abhi0049k** [comment]
for sure @Luson045. Thank you for assigning this issue to me

**Comment by Luson045** [comment]
@Abhi0049k  updates??

**Comment by sriraghavi22** [comment]
Hey can i work on this issue?

**Comment by Abhi0049k** [comment]
Hi @Luson045, I apologize for the delays. My exams are currently ongoing, which is causing the hold-up, but I have started working on the issue.

**Comment by Abhi0049k** [comment]
I am currently trying to use Recoil to manage global state in the app, so we can manage the modes and toggle between them. However, I am facing an error that is causing a delay. I will try to complete this by today or tomorrow, and I will raise a PR then.

**Comment by Luson045** [comment]
@Abhi0049k okay i can understand that even i am going thorugh exams... take your time but make sure when you give pr you have the latest changes in your PR

**Comment by Abhi0049k** [comment]
@Luson045 Thank you

**Comment by shanmukhi-developer** [comment]
Can I add the dark mode and light mode toggle to enhance the user experience
