### ISSUE TITLE
Refactor Backend Code for Better Structure and Readability

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description:
The current backend code has several long and complicated files that handle too many tasks at once, making it hard to understand and maintain. I want to improve the code's structure while keeping everything working the same way.

**Objectives:**
- **Break It Down**: Split large files into smaller, focused pieces that do one thing well.
- **Organize Files**: Rearrange the file structure to make it easier to find related parts of the code.
- **Clear Naming**: Use simple and consistent names for variables, functions, and files to improve clarity.

By making these changes, we aim to create a cleaner and more manageable codebase that will be easier to work with in the future.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@tejasbenibagde okay
