### ISSUE TITLE
[Feat] Enhancing password security by including atleast one capital letter, number, special character 

### ISSUE THREAD

**Issue by LitZeus** [Luson045/medi-connect#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance password security by enforcing a policy that requires at least one uppercase letter, one number, and one special character, ensuring stronger protection against unauthorized access

### Use Case

By implementing this feature, the project will significantly reduce the likelihood of weak password creation, enhancing user account protection against brute force attacks. It will ensure that all passwords meet a minimum security threshold, reducing the risk of unauthorized access and safeguarding sensitive user data stored within the system. This will improve overall trust and reliability in the project's user authentication process.

### Benefits

- Enhanced Security: Enforcing stronger password requirements reduces the risk of account breaches, protecting users' sensitive information from attacks such as brute force and dictionary attacks.

- Compliance with Best Practices: The feature aligns with industry standards for password security, helping the project adhere to cybersecurity best practices and regulations.
 
- Increased User Trust: By prioritizing security, users will feel more confident in using the platform, knowing their accounts are well-protected.
 
- Reduced Support Burden: Stronger passwords reduce the likelihood of compromised accounts, minimizing the need for password recovery or account restoration support.
 
- Scalable Security: As the user base grows, this feature ensures that security measures are consistently applied across all accounts, maintaining a secure environment for the entire community.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
okay @LitZeus
