### ISSUE TITLE
[Bug] Menu bar is not responsive in mobile view

### ISSUE THREAD

**Issue by Rahul7raj** [Luson045/medi-connect#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The menu bar is not responsive in mobile view especially, the login and register buttons in menu bar

### Add Screenshots

![image](https://github.com/user-attachments/assets/49a9f934-cd92-4c9e-9ca7-746442b89590)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Rahul7raj** [comment]
@Luson045 please assign it to me. i can fix it

**Comment by ROKUMATE** [comment]
@Rahul7raj complete it by the end of tomorrow

**Comment by huzaifsk** [comment]
@Rahul7raj  can you please assign this to me. I can solve this issue
