### ISSUE TITLE
[Bug] Want to  change the footer and gives it a better look

### ISSUE THREAD

**Issue by ark0078** [Luson045/medi-connect#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The look of the footer is not matching.I just want to change it and give a better look,since this project is superb just
![Screenshot (219)](https://github.com/user-attachments/assets/c5cc14f5-e6c7-4948-b6bd-56d42d2e3c2f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@ark0078 sorry not needed
