### ISSUE TITLE
write a code of conduct which looks exquisite and gives a proper explaination to contributor

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#30]
1) read the announcement section
2)read the about of the project
3) search on google

and make a CODE_OF_CONDUCT.md file for medi-connect repo

**Comment by Itachii27** [comment]
Hi @Luson045 I want to work on this issue. Please assign this issue to me.

**Comment by Luson045** [comment]
done 👍

**Comment by Itachii27** [comment]
Hi @Luson045 I have done. Kindly review the PR.
