### ISSUE TITLE
[Feat] Can I add a CONTACT US tab so that interaction can be enhanced?

### ISSUE THREAD

**Issue by ark0078** [Luson045/medi-connect#300]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Feature Description

I'd like to add a contact us tab then visitors can visit and ask their questions using that form

### Use Case

It would add more interactivity to the visitors and they can ask questions with ease

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ark0078** [comment]
@Luson045 can you assign me this issue?possible?

**Comment by Luson045** [comment]
issue already exists #214 , please don't click the checkbox without doing so
