### ISSUE TITLE
[Feat] : Implement strong password validation in the registration form

### ISSUE THREAD

**Issue by bj-jiwrajka** [Luson045/medi-connect#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the registration form allows weak passwords without validation. There is no check for password strength, which could lead to insecure accounts.

Add a password strength check that validates the following criteria:

-     Minimum length of 8 characters.
-     At least one uppercase letter.
-     At least one lowercase letter.
-     At least one number.
-     At least one special character (e.g., !@#$%^&*).

### Use Case

Implementing a strong password validation check would ensure better security for users.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by bj-jiwrajka** [comment]
@Luson045 @ROKUMATE As discussed in the earlier issue conversation (https://github.com/Luson045/medi-connect/issues/264#issuecomment-2399025342), I am creating a new issue for validating strong pw checks. Please allow me to do it.

**Comment by Luson045** [comment]
tthere's already a pr for that, i think this issue is not required now
