### ISSUE TITLE
[Feat] Multilingual Support to the media-connect

### ISSUE THREAD

**Issue by IkkiOcean** [Luson045/medi-connect#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to integrate Google Translator into the medi-connect web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Use Case

Allow users to translate all pages of the midi-connect application into their preferred language using Google Translator.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@IkkiOcean exactly!! i wan also thinking to apply this.. You can proceed with this issue.
