### ISSUE TITLE
Rename 'frontend' to 'client' and 'backend' to 'server' in documentation

### ISSUE THREAD

**Issue by CodexRaunak** [Luson045/medi-connect#31]
![image](https://github.com/user-attachments/assets/de6bee76-d85f-427f-b51a-40d337e43310)

### We need to update our documentation to reflect the following changes:

1. Rename of 'frontend' to 'client'.  (cd client)
2. Rename of 'backend' to 'server'. (cd server)
3. And 'cd hospital-management-system' should be cd medi-connect

**Comment by CodexRaunak** [comment]
Can I work on this?

**Comment by Luson045** [comment]
sorry to say but this issue is already taken care of in other issue

**Comment by CodexRaunak** [comment]
Ohh sorry , I didn't checked kt
