### ISSUE TITLE
[Bug] Add hover effect to homepage

### ISSUE THREAD

**Issue by devarsheecodess** [Luson045/medi-connect#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The options on header are not looking good without hover effects, i want to work on this issue, assign me this issue under gssoc-extd, hacktoberfest-accepted and level2 labels

### Add Screenshots

![image](https://github.com/user-attachments/assets/f6633207-f632-43b7-adaf-48789d9e8b29)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by amrahs02** [comment]
Hey @devarsheecodess  can I work on this?

**Comment by Luson045** [comment]
too much of animation looks bad.... so not needed yet
