### ISSUE TITLE
[Bug] Missing Navbar and Footer on Lab Test Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [Luson045/medi-connect#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

On the Lab Test page, both the navigation bar and the footer are missing. This creates an inconsistent user experience, as the rest of the site includes these components. Additionally, the absence of the navbar makes it difficult for users to navigate back to other sections of the site.

### Add Screenshots

![Screenshot 2024-10-09 005045](https://github.com/user-attachments/assets/2766e033-465b-4eeb-b7ea-45b963beed9e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by MadeshiAshlesha** [comment]
@Luson045 I would like to work on this issue, Can you please assign this to me?

**Comment by Trevisx07** [comment]
@MadeshiAshlesha Go with it!
And make sure to make it same as the other pages, don't try anything different.

**Comment by MadeshiAshlesha** [comment]
can you please add my as an assignee?

**Comment by MadeshiAshlesha** [comment]
okay

**Comment by Luson045** [comment]
@MadeshiAshlesha can you also add it in Blog.jsx

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 can you also add it in Blog.jsx

Sure, I will add it to the blog page as well
