### ISSUE TITLE
[Bug] navbar not sticking to the top after scrolling back up

### ISSUE THREAD

**Issue by IkkiOcean** [Luson045/medi-connect#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The navbar does not stick to the top of the viewport when scrolling back up the page. This behavior affects user experience, as users expect the navbar to remain accessible at all times.

### Add Screenshots

<img width="1276" alt="Screenshot 2024-10-09 at 1 54 48 AM" src="https://github.com/user-attachments/assets/acafde6a-c459-4dec-b29c-7e08608172f2">

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
i dont want it to be sticky, it shows up as soon as you scrolll up
