### ISSUE TITLE
[Feat] Improving the UI of footer

### ISSUE THREAD

**Issue by Suvadip-sana** [Luson045/medi-connect#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Along with whole website POV, the footer is too simple for now.
It should be better visually appealing like this - 

https://github.com/user-attachments/assets/2a625cf7-7cd5-442d-9bb7-02a5b3c57e92

Could you please assign me for this task?

### Use Case

For implementing this, The UX would be much better for user.
*NOTE* I am an hacktober participant, So please add this label if you assign to me.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Suvadip-sana okay but make sure to not to add gif's or something.. as it increases the loading time

**Comment by Suvadip-sana** [comment]
Sure. 
Please add the label -2 or 3, because it's need to design from scratch
After that I start working on it.

**Comment by Luson045** [comment]
Level will be given based on the design..

**Comment by Suvadip-sana** [comment]
@Luson045 
Okk. 
Thank you. I am going to start working on it.

**Comment by Suvadip-sana** [comment]
@Luson045  Could you please provide me your social media links?

**Comment by Suvadip-sana** [comment]
@Luson045 
I complete this task. It also responsive for mobile. 
In copyright section the year is dynamic. Also add the default 'Page not found' page, which pages are missing on it.
If you send me your social media link then I add this.


https://github.com/user-attachments/assets/9528a888-2714-4458-ade0-50537f02a9e1


After adding the disclaimer 
![image](https://github.com/user-attachments/assets/59947f5a-27cb-411e-bd04-59d54da1b9f4)

Please go through it, tell me what you think?
Then I make a pull request. 
@Luson045

**Comment by Luson045** [comment]
@Suvadip-sana it's okay no need to add links now, you can give pr

**Comment by Suvadip-sana** [comment]
Okk.

**Comment by Luson045** [comment]
if you give a pr with no merge conflicts, i'll give three else 2 👍
