### ISSUE TITLE
[Add Marquee Animation ] Ading a marquee Animation from right to left for all reviews given by user at slow speed  

### ISSUE THREAD

**Issue by dev129** [Luson045/medi-connect#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Instead of User Clicking more and more, adding a marquee Animation can help a lot. Making ita better UX 

### Use Case

This will be beneficial in viewing what other people say about the service, without clicking the arrow button

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@dev129  Sorry, I think it's better this way.
