### ISSUE TITLE
[Bug] Load More button 

### ISSUE THREAD

**Issue by subrataCS** [Luson045/medi-connect#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

Load More button text color becoming white while hover , its not looking good want to change it .

@Luson045 please assign it to me if its not assigned to anyone else & add the relevant tags .

### Add Screenshots

![image](https://github.com/user-attachments/assets/2923dd4f-f563-43c3-9fa0-163694b2991f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
okay @subrataCS , also enhance the load time of this page, it takes quite some time to load
