### ISSUE TITLE
[Feat]: Responsive Progress Bar Implementation

### ISSUE THREAD

**Issue by Trevisx07** [Luson045/medi-connect#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementation of a visually engaging and responsive progress bar for the website.

Details:
The progress bar should be designed to match the current theme and style of the website, ensuring a seamless integration with the existing UI.
It should be visible and functional on both desktop and mobile views, adapting its size and placement for different screen resolutions.

Examples:
![image](https://github.com/user-attachments/assets/3ddb60f6-b577-485a-b555-ef7b83e75f20)

### Use Case

-

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Trevisx07** [comment]
Anyone willing to work on this...!

**Comment by lade6501** [comment]
I can take.

**Comment by Trevisx07** [comment]
@lade6501 Okay...Go with it!
