### ISSUE TITLE
Design an implementation plan for medi-connect in real world

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#33]
Hey there, so this is a no code issue, where you task is to design a complete roadmap for the implementation of medi-connect...

1) do some SWOT analysis of medical sector in india
2) Create a strategy to implement medi-connect
3) list competitors and their shortcomings
4) design a pricing strategy
5) design marketting strategy 
6) brainstrom 🧠

this issue will be assigned to 3 contributors as the work is largs

if the file is made like the README.md file and CONTRIBUTOR.md file in this repo, i.e. using rich text of .md file then I will give it a "level 2"

**Comment by mienpham04** [comment]
Hey can you assign that to me?

**Comment by Luson045** [comment]
done 👍

**Comment by Rizvi-Faiz** [comment]
@Luson045 can you assign this to me

**Comment by ROKUMATE** [comment]
@Rizvi-Faiz i am assigning this issue to u ... if anyone else joins i will assign them with u ... 

till then try to complete it and submit by the end of tomorrow if possible .... 
if you want extension in deadline do tell so.

**Comment by Rizvi-Faiz** [comment]
@ROKUMATE sir I should submit a mark down file for road map ??

**Comment by ROKUMATE** [comment]
@Rizvi-Faiz if you give the roadmap in .md file then i will label the issue to be level 2
