### ISSUE TITLE
[Feat] Add Navbar and Footer to lab test page

### ISSUE THREAD

**Issue by Anwishta** [Luson045/medi-connect#330]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Feature Description

This feature request is to add a navbar and footer to the Lab Test page, ensuring consistency in design and navigation across the website. The navbar will allow users to navigate easily across the site, while the footer will provide essential information such as contact details, privacy policies, and links to other important pages.

### Use Case

 Keeps the design uniform across all pages.
The footer provides important links like terms, privacy policies, and social media, building trust.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Luson045  I already told you to 🥲

**Comment by Luson045** [comment]
@Anwishta someone else is assigned this issue...
