### ISSUE TITLE
[Bug] remove the scrollbar from below

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

quick fix

### Add Screenshots

<img width="960" alt="image" src="https://github.com/user-attachments/assets/f37cac9e-884e-4af8-8218-f7202b978b08">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [ ] I want to work on this issue (Optional)
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Suraj-kumar00** [comment]
Hi @Luson045, As I'm interested in working on the navbar issue i'll work on this issue as well,
Can you please assign it to me?

**Comment by AnshMehta24** [comment]
Hi @Luson045  ,  Can you please assign this issue to me?
I Would like to work on this.

**Comment by Luson045** [comment]
@Suraj-kumar00 okay 👍

**Comment by Luson045** [comment]
@AnshMehta24 sorry you're late

**Comment by AnshMehta24** [comment]
Hi @Luson045 , I see someone else has been assigned the task I was interested in. However, I’d still like to try solving it as part of my learning process. If I complete it before the other contributor, I’d appreciate it if you could consider my solution. Thanks!

**Comment by Suraj-kumar00** [comment]
Hi @AnshMehta24, how have you been?
You have to understand that's not how the open source community work! this is not the standard.

**Comment by AnshMehta24** [comment]
It's my first time. I'll Keep that in mind bro.

BTW just add overflow-x:hidden in the body tag. so it will work fine in this issue. i have checked using devTools.

**Comment by Suraj-kumar00** [comment]
Hi @Luson045, how have you been?
I think this issue is also fixed, please close this issue also.

**Comment by Luson045** [comment]
ohh okay 👍
