### ISSUE TITLE
[Feat] Redesigning the UI of the login page which should be ideally relevant to the navbar

### ISSUE THREAD

**Issue by rebornstar1** [Luson045/medi-connect#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current UI of the login page does not align with the overall design and aesthetics of the navbar, leading to a disjointed user experience. This inconsistency can confuse users and diminish the professional look of the website.

### Use Case

When users arrive at the login page, they expect a design that is coherent with the rest of the site. A login page that reflects the navbar's style will provide users with a familiar and intuitive interface, making the login process more straightforward.

### Benefits

Consistency in Design: A redesigned login page that matches the navbar enhances the overall visual harmony of the website, making it more appealing.
Improved User Experience: A cohesive design helps users feel more comfortable and confident while navigating the site, reducing cognitive load.
Increased Trust and Credibility: A professional-looking login page fosters trust among users, encouraging them to engage more with the site and its offerings.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@rebornstar1 👍🏻
