### ISSUE TITLE
The scroll bar of your website is not looking good and it is default which is not suited in your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#34]
https://github.com/user-attachments/assets/fa545210-e2db-430d-b824-04359cb04da3

The side scroll  bar is not looking good on website I want to make it good UI like this below video with your website suited colour.

https://github.com/user-attachments/assets/b434cdca-5b21-46c9-b702-7d741f1fb445

so assign this issue under gssoc extended and hactoberfest.

**Comment by Luson045** [comment]
yeah agree, you got this 👍

**Comment by varma-101** [comment]
i would like to work this

**Comment by VinayLodhi1712** [comment]
> yeah agree, you got this 👍

thankyou i will work on it. and @varma-101 sorry but this issue is assigned and i am just working on it.

**Comment by Luson045** [comment]
@varma-101 as per the guidlines it's first come first serve, please find some other issues, I would be more than happy to see wider variety of issues
