### ISSUE TITLE
[Feat] : Add ESLint and Integrate with Prettier for Code Consistency in Backend

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey team, I noticed that the backend currently uses **Prettier** for code formatting, but **ESLint** isn’t set up yet. Prettier does a great job at keeping our code neat, but it doesn’t handle things like catching errors or enforcing coding standards.

By adding ESLint and integrating it with Prettier, we can maintain our formatting standards and also make sure that the code is following best practices, is free of common mistakes, and has better overall quality. This will help reduce the number of issues that come up during code reviews and will make it easier to maintain clean and consistent code throughout the project.

### Use Case

Here’s why we should add ESLint:
- We can catch bugs and potential issues early during development.
- We can enforce consistent coding standards across the team, making it easier to collaborate and review code.
- We’ll reduce the amount of time spent on nitpicky formatting or style changes during code reviews since both Prettier and ESLint will automatically handle that for us.

### Benefits

It will keep the codebase clean ✨

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by lade6501** [comment]
Hi @tejasbenibagde this issue is resolved, we have already added a pre-commit hook for both frontend and backend #274.

**Comment by tejasbenibagde** [comment]
Oh I did not see that sorry.
