### ISSUE TITLE
Implement the instant OPD feature, try to enhance it. 

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#35]
when instant OPD form is filled.... Nothing happens! As of now, we haven't implemented the instant OPD feature

implement the instant OPD feature
flow:
1)user inputs data
2)fetch the hospital in the same address
3)book an appointment there[ mark it as URGENT]
4)return the hospital data and address to the user

If there was something more than level 3 i would've assigned this issue as that 😅
Make sure you're a good backend developer before opting for this issue

**Comment by varma-101** [comment]
I would like to work on this

**Comment by ShaikHafiza** [comment]
i would like to work on this

**Comment by Luson045** [comment]
it's a level 3 issue @varma-101 you must be really good with node and express for this issue? are you sure you can do this?

**Comment by Luson045** [comment]
only opt for this if you are confident with yourself

**Comment by tanish35** [comment]
Hi can i be assigned to do this

**Comment by varma-101** [comment]
Can i get api for fetching the data.if so i can work on it please send me regards.

**Comment by Luson045** [comment]
@varma-101 no, there's no api yet, as i mentioned it's a backend issue you have to design and make the api :) @tanish35 are you good with that?

**Comment by varma-101** [comment]
i have quite an experience with backend,but i need an api to fetch hospital data. rather than using third party api's which may not give accurate data about nearby hospitals.

**Comment by tanish35** [comment]
Yeah sure @Luson045 i can use osm and osrm to figure out the distance and also convert the pincode to lat long

**Comment by Luson045** [comment]
@tanish35 cool that's a great idea, you can make changes in the schema to add lat and long and pincodes, ill assign this to you, do you want other contributors to join you?

**Comment by Somnath-Chattaraj** [comment]
I will be working with @tanish35 at this issue

**Comment by tanish35** [comment]
Yeah you can assign @Somnath-Chattaraj to this also

**Comment by Luson045** [comment]
@tanish35 remove user verification here and just mark it as an emergency case use all the details peovided  by the form only
router.post(
  "/emergency",
  authenticateToken,
  asyncHandler(async (req, res) => {
    const { pincode, reason, date } = req.body;
    if (!pincode) {
      return res.status(400).json({ message: "Pincode is required" });
    }
    const results = await geocoder.geocode(pincode + " India");
    if (results.length === 0) {
      return res.status(404).json({ message: "Location not found" });
    }
    const userLat = results[0].latitude;
    const userLong = results[0].longitude;
    const hospitals = await Hospital.find({}, { lat: 1, long: 1, _id: 1 });
    let minTime = Infinity;
    let nearestHospital = null;
    for (let hospital of hospitals) {
      const hospitalLat = hospital.lat;
      const hospitalLong = hospital.long;
      const route = await axios.get(
        `https://router.project-osrm.org/route/v1/driving/${userLong},${userLat};${hospitalLong},${hospitalLat}?overview=false`
      );
      const time = route.data.routes[0].duration;
      if (time < minTime) {
        minTime = time;
        nearestHospital = hospital;
      }
    }
    const profile = await User.findById(req.user.id);
    if (!profile) {
      return res.status(404).json({ msg: "Profile not found" });
    }
    const appointment = {
      userId: req.user.id,
      date,
      reason,
      status: "pending",
    };
    try {
      const hospital = await Hospital.findById(nearestHospital._id);
      hospital.appointments.push(appointment);
      profile.appointments.push(appointment);
      await hospital.save();
      await profile.save();
      await sendMail(
        `Your appointment has been booked at ${hospital.name} on ${appointment.date}`,
        profile.email
      );
      res.status(200).json({
        message: "Appointment booked successfully",
        appointment,
        hospital: {
          id: hospital._id,
          name: hospital.name,
        },
      });
    } catch (error) {
      res.status(500).json({ message: "Error booking appointment", error });
    }
  })
);

module.exports = router;

@Somnath-Chattaraj make required changes in the form, add pin code and other details required in this api call and change the current api call of instant OPD to this one

**Comment by tanish35** [comment]
ok will do it
