### ISSUE TITLE
[Bug] : Modularity Issues in a Backend Directory

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Overview

- The current backend code is stored in a single directory, `modules`, which makes it difficult to understand the purpose of various files and the overall folder structure.
- To enhance modularity and readability, I propose the following changes:
  - Create separate directories for different components:
    - `controllers`
    - `routes`
    - `validations`
    - `utils`
    - `lib`
- This restructuring will clarify the organization of our code while maintaining the same functionality.

### Add Screenshots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@tejasbenibagde let the codes be in module only, what you can do is inside the modules. you can create separate routes and controller file. for each module

**Comment by Luson045** [comment]
@tejasbenibagde make sure none of the functionality is changed, in which case we'll revert the changes 👍
