### ISSUE TITLE
[Feat] 

### ISSUE THREAD

**Issue by neerajsharma897** [Luson045/medi-connect#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/3c3eb266-2109-4ee9-a344-61682b1cf646)
when i visted your blog page the UI seemed and there was no back button to lead to main page 

### Use Case

I would use plain css or bootstrap to improve the UI and 
add a "a href tag" that will lead to main page 

### Benefits

easier navigation page and better apeal to users

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by neerajsharma897** [comment]
pls assign this under the gssoc extended and hactober fest

**Comment by Luson045** [comment]
@neerajsharma897 sorry but we have added navbar to that page now this issue  is fixed

**Comment by neerajsharma897** [comment]
okay thanks
