### ISSUE TITLE
[Bug] someone made the navbar sticky

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

the navbar used to move up when scrolled down and move down when scrolled up, now in some recent changes, someone changed it to be sticky, you need to fix it in this issue also navbar is looking very full fix it too.
<img width="960" alt="image" src="https://github.com/user-attachments/assets/e84979d0-6172-489c-ae5a-7a10f4a11093">

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC contributor
- [x] I want to work on this issue (Optional)
- [x] I'm willing to provide further clarification or assistance if needed.

**Comment by Suraj-kumar00** [comment]
Hi @Luson045, Can you please assign this issue to me?
I Would like to work on this.

**Comment by Luson045** [comment]
@Suraj-kumar00 okay 👍

**Comment by AnshMehta24** [comment]
Hi @Luson045 , Can you please assign this issue to me?
I Would like to work on this.
