### ISSUE TITLE
Add Login and Signup Routes with Passport.js Authentication

### ISSUE THREAD

**Issue by varma-101** [Luson045/medi-connect#36]
Implement user authentication in the Node.js and Express.js backend using Passport.js. This task involves setting up secure login and signup routes that will handle user registration, login, and session management. The implementation should follow best security practices.

Requirements:
Signup Route (/signup):

Create a POST route for user registration.
Use Passport.js local strategy to handle user signup.
Hash user passwords using PBKDF2 with a salt and store them in the database (e.g., MongoDB).
Validate input fields like username, password, and email.
Return appropriate success or error messages.
Login Route (/login):

Create a POST route for user login.
Authenticate users using the Passport.js local strategy.
Check credentials against hashed passwords stored in the database.
Return appropriate error messages for invalid login attempts.
Passport.js Configuration:

Set up Passport.js with the local strategy for username and password authentication.
Ensure that passwords are compared securely with the stored hash using the Node.js crypto library.
Use passport.serializeUser and passport.deserializeUser to manage user sessions.
Session and Security:

Manage user sessions using Express-session.
Ensure sessions are secured, especially in production environments (e.g., use HTTPS, secure cookies).
Implement necessary middleware for session handling.

**Comment by ShaikHafiza** [comment]
I would like to work on this along with @varma-101  to make work easier

**Comment by Luson045** [comment]
@ShaikHafiza it's postponed

**Comment by Luson045** [comment]
make sure not to give pr for this right now any pr for this one won't be accepted until the other work in this field are over

**Comment by varma-101** [comment]
Thanks for your consideration. i will try to deliver this fast.i will discuss with @ShaikHafiza and contribute together.
And could you please mention me the deadline for this pr.

**Comment by Luson045** [comment]
There's no deadline, i will remove the postponed tag nearly by 7th october, so that things get stable by then, so then you can start working on it

**Comment by ShaikHafiza** [comment]
Thankyou @Luson045 I'll do my best.

**Comment by Luson045** [comment]
@varma-101 @ShaikHafiza any updates on this,??

**Comment by ShaikHafiza** [comment]
Work is going on @Luson045

**Comment by Luson045** [comment]
@if it is taking time you guys can first focus on issue #44 and #38 @varma-101 @ShaikHafiza

**Comment by ShaikHafiza** [comment]
Ok @Luson045

**Comment by Luson045** [comment]
@ShaikHafiza @varma-101 yea but please complete those two issues fast

**Comment by Luson045** [comment]
Sorry to say this issue is not more needed to work upon.
