### ISSUE TITLE
[Bug] : Missing Footer on Hospitals Around Page

### ISSUE THREAD

**Issue by rajgharat07** [Luson045/medi-connect#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

Bug Description:

- Issue : The footer component is missing from the "Hospitals Around" page, which leads to an inconsistent user experience as the footer is present on other pages of the application.

- Expected Behavior : The footer should be displayed on the "Hospitals Around" page, providing users with access to important links, contact information, and navigation options that are available on the other pages.

- Impact : Users may face difficulty accessing site-wide information like contact details or other resources typically found in the footer, and the overall layout feels incomplete on this page.

- Steps to Reproduce :
  - Navigate to the "Hospitals Around" page.
  - Scroll to the bottom of the page.
  - Observe that the footer is not displayed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
not needed
