### ISSUE TITLE
[Bug] : Light/Dark Toggle Theme not working as expected on Login/Register Pages Buttons Click

### ISSUE THREAD

**Issue by rajgharat07** [Luson045/medi-connect#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

Bug Description :

- Issue : The light/dark theme toggle is not functioning properly when interacting with the "Login" or "Register" buttons. Despite switching between light and dark modes elsewhere in the app, the theme does not consistently apply to these buttons, causing them to appear with incorrect colors or styles that do not match the selected theme.

- Expected Behavior : When the theme toggle is activated, the "Login" and "Register" buttons should dynamically update their appearance according to the selected light or dark theme, maintaining consistency across the application.

- Impact : The inconsistent behavior affects user experience, as the buttons may remain in the wrong theme mode, making them harder to read or use, especially in dark mode.

- Steps to Reproduce :

  - Navigate to the login or registration page.
  - Toggle between light and dark mode.
  - Observe that the "Login" or "Register" buttons do not reflect the theme change properly.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@rajgharat07 didn't you gave pr for this already?

**Comment by rajgharat07** [comment]
@Luson045 Please assign me this issue under GSSOC and Hacktoberfest labels

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd
