### ISSUE TITLE
[Feat] Modification of README.md file

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [Luson045/medi-connect#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 1) Add animated line separators
Add animated line separators in between sections and also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.

![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/dbda1abf-f2d6-490c-b6f8-6152f600e878)

The Team section will look more organized and readable and let the Contributors know whom to contact if they face any issues.

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 1) Add animated line separators
It will make the project organized and attractive.

### 2) Replace the Contact section  with a **Team section**
The Team section will be visually appealing for the Contributors and also help them know who to reach out when needed. 

### 1) Add animated line separators
I think adding this banner along with the animated lines will make it not only look more attractive but also increase the readability of the repository.

### 2) Replace the Contact section  with a **Team section**
The new **Team section** will look more organized and increase the readability and scalability of the project. This will make the project attractive as the Contributors would land on the **README.md** page first and see the Team section.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
okay

**Comment by rajdeepchakraborty-rc** [comment]
@Luson045 While working , I noticed that the Contributor mention section is not updated.
![image](https://github.com/user-attachments/assets/a5ff6dd0-c006-4cfa-8500-7a085c4b7ca9)

I can try to automate the updation process since I am working on the README.md file. If you want me to work on that, please let me know.

**Comment by rajdeepchakraborty-rc** [comment]
This is how the Team Section is looking for you:

![image](https://github.com/user-attachments/assets/5599c823-80bd-4553-9062-fe2475a6b678)

**Comment by Luson045** [comment]
@rajdeepchakraborty-rc  okay tht would be great

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc okay tht would be great

@Luson045 Is this reply about the Contributor mention section?

**Comment by Luson045** [comment]
Yes 👍🏻

**Comment by rajdeepchakraborty-rc** [comment]
> Yes 👍🏻

@Luson045 Ok I will also work on that then. I would kindly ask you to assign the issue level2 since I am working on the automation too.

**Comment by rajdeepchakraborty-rc** [comment]
I have updated the banner section for both GSSoC and Hacktoberfest:
![image](https://github.com/user-attachments/assets/8298dfc3-2ffa-4445-84c9-3d4158a18933)

**Comment by rajdeepchakraborty-rc** [comment]
This is the updated Contributors mention section:

- Before
![image](https://github.com/user-attachments/assets/1a2fec69-3bd8-403e-aba2-a4971f73f167)

- After
![image](https://github.com/user-attachments/assets/3796a229-6280-4c3e-92f5-5e7c9ad2f1d1)

**Comment by rajdeepchakraborty-rc** [comment]
I will open a PR shortly and let you know.

**Comment by rajdeepchakraborty-rc** [comment]
Closed this issue as accepted and merged in PR #403
