### ISSUE TITLE
Design the Profile Page of users

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#37]
redesign the profile page of users, keep the same colour theme

**Comment by Aiu26** [comment]
@Luson045 can i work on this under hacktoberfest?

**Comment by Luson045** [comment]
@Aiu26 done 👍

**Comment by Luson045** [comment]
@Aiu26 
![Screenshot_2024-10-02-10-28-57-50_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/bedfb816-2ee3-492e-9d10-5a871d533eae)

It's not responsive, work on it please

**Comment by Aiu26** [comment]
Sure, i will work on it
