### ISSUE TITLE
[Feat] UI enhancement and bug fixing in ABOUT US

### ISSUE THREAD

**Issue by Bhum-ika** [Luson045/medi-connect#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/9325ab08-c319-461d-ab0d-9376b7b7c1fa)
**The cards should be of same size and image must be in center. Also the about us page is quite basic. I would like to enhance its UI**

### Use Case

As the whole website is really attractive, about us page given info about the website, holds info about contributors which should look excellent too.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Bhum-ika okay you can work on it 👍🏻

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd

**Comment by Bhum-ika** [comment]
@SatyamTiwari069 This is already assigned to me
