### ISSUE TITLE
[Bug]: Fix this placing

### ISSUE THREAD

**Issue by Trevisx07** [Luson045/medi-connect#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

i want the chatbot button aligned just above the scoll-to-top button with slight gap perfectly for both desktop as well as mobile view. Currently its not aligned. Fix it.
![image](https://github.com/user-attachments/assets/99ae9dc5-e9ff-4ac0-9562-f50ae1976db9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [ ] I want to work on this issue (Optional)
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by lade6501** [comment]
I can take it. Will fix it along with #328

**Comment by Trevisx07** [comment]
Okay!
