### ISSUE TITLE
[Bug] Quick refresh after api call (user can't read error message)

### ISSUE THREAD

**Issue by sameer-soni** [Luson045/medi-connect#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

https://github.com/user-attachments/assets/ec78d560-b3eb-49e6-b8da-fa5985453168

After clicking on register, there's an error but the site refreshes quickly and user can't read the error message properly.
my solution-> delaying the page reload.
I'm interested in solving this issue, please assign me and add the gssoc/hactoberfest label.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
Okay fix it @sameer-soni

**Comment by sameer-soni** [comment]
@Luson045 I have fixed this, please add the hacktoberfest-accepted and gssoc-ext label before merging it.
