### ISSUE TITLE
Inconsistent plqcrmnt of scroll to top button In mobile view

### ISSUE THREAD

**Issue by shubhagarwal1** [Luson045/medi-connect#375]
![image](https://github.com/user-attachments/assets/eade5f00-511f-40f1-be47-57b7ed04df67)
Here scroll is placed above the chat bot with no margin and padding,

**Comment by lade6501** [comment]
Hi @shubhagarwal1 we already have issue for that  #371

**Comment by shubhagarwal1** [comment]
Hey @Luson045 do you have any availble tasks that i can work on or anythingin your mind that you find to be fixed
