### ISSUE TITLE
The chatbot is not working

### ISSUE THREAD

**Issue by Suraj-kumar00** [Luson045/medi-connect#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

When I tried to communicate with chat bot it's saying:
"Sorry, I encountered an error. Please try again later."

Maintainer please discuss about this issue, I think this is related to `api key`

### Add Screenshots

![image](https://github.com/user-attachments/assets/ddbae837-51f6-4ab3-99a3-9e4627577e6c)

### What browsers are you seeing the problem on?

- Brave
- Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
Yes we haven't provided an api key yet, you can make a Gemini api key and add it there.

**Comment by Suraj-kumar00** [comment]
> Yes we haven't provided an api key yet, you can make a Gemini api key and add it there.

I think the API key should be your for the security purposes and to be safe.
So either you can add it or you can send me and I'll fix that!

**Comment by lade6501** [comment]
Hi @Suraj-kumar00 , you can create a Gemini API and add that to your .env for local testing, currently it's not pushed to demo app.

**Comment by Suraj-kumar00** [comment]
> Hi @Suraj-kumar00 , you can create a Gemini API and add that to your .env for local testing, currently it's not pushed to demo app.

So should I work on this issue? If yes please assign it.

**Comment by Luson045** [comment]
no no it's fine.
