### ISSUE TITLE
ADD the github team in about us section

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#38]
make a new card, add title the github team

where I can mention all the github contributers along with their github profile image

<img width="960" alt="image" src="https://github.com/user-attachments/assets/a6505685-133f-4ccb-87bd-da2a2f7752dd">

before OUR VISION

**Comment by ShaikHafiza** [comment]
Yes, I would like to work on this.

**Comment by Luson045** [comment]
done 👍

**Comment by varma-101** [comment]
can i also be a part of this.

**Comment by Luson045** [comment]
I already offered you!! It's always first come and if you can serve, then first serve... I don't think this issue needs 2 contributers, please raise a new and unique issue if you want to contribute

**Comment by varma-101** [comment]
Ok.

**Comment by Luson045** [comment]
@ShaikHafiza updates??

**Comment by Luson045** [comment]
@ShaikHafiza I'm reassigning this issue to others today, if no updates are provided, also outdated features will be rejected.

**Comment by ShaikHafiza** [comment]
@Luson045  Sorry for the delay.. I'll surely give updates on this upto evening

**Comment by Luson045** [comment]
okay but make sure you have the latest changes in your pr, else i won't provide any more flexibility in time
