### ISSUE TITLE
[Bug] Registration page

### ISSUE THREAD

**Issue by iamsyg** [Luson045/medi-connect#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

All the entered details must not disappear when the entered credentials do not meet the valid format after clicking on submit, and it must show a proper error message instead of reloading.

### Add Screenshots

https://github.com/user-attachments/assets/b1cb1615-9ef4-4d53-9880-f14d1c395cea

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
ohh, you can work on it

**Comment by lade6501** [comment]
Hi @Luson045  issue is fixed in #385

**Comment by Luson045** [comment]
okay 👍 actually i was checking from top
