### ISSUE TITLE
[Bug] : setBasicDetials is not a function error while registering. 

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

Someone renamed the setter function in context file but didn't change it in the `Registration`  component. Which is throwing an error while trying to register.   

### Add Screenshots

<img width="1438" alt="Screenshot 2024-10-11 at 10 47 20 PM" src="https://github.com/user-attachments/assets/86898c05-7e34-4ddc-9f1f-701cf732cadd">

### What browsers are you seeing the problem on?

Chrome, Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by coder483** [comment]
gonna fix it really quick

**Comment by lade6501** [comment]
Hi @coder483 I'm working on this.

**Comment by coder483** [comment]
you got another issue for me to solve ?

**Comment by VinayLodhi1712** [comment]
guys plz solve it quickly as possible as i am not able to work on my issue

**Comment by lade6501** [comment]
> guys plz solve it quickly as possible as i am not able to work on my issue

Hi @VinayLodhi1712  till PR is  merged you can change`setBasicDetials` function to `setBasicDetails` in `StepOne.jsx` file in your localhost.

**Comment by Luson045** [comment]
@lade6501 thanks for looking into this 👍
