### ISSUE TITLE
[Feat] hospital around page card design for the list of hospitals below the map.

### ISSUE THREAD

**Issue by Shariar-Hasan** [Luson045/medi-connect#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- i will try to create a probably better card design, as these does not have any card design right now

### Use Case

- this cards will provide a better look in the hospital around page

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Shariar-Hasan** [comment]
![image](https://github.com/user-attachments/assets/b756639b-9d8d-41e8-aeef-5493a32ece19)

**Comment by Trevisx07** [comment]
@Shariar-Hasan Means you would be creating cards below the map section of all hospitals nearby, am i right?

**Comment by Shariar-Hasan** [comment]
Yes it is.

**Comment by Trevisx07** [comment]
@Shariar-Hasan Okay!...Go with it and try to make designs simple and make sure that it matches the overall design of website.
Also when making PR attach screenshot/video with it.

**Comment by Shariar-Hasan** [comment]
ok, got it

**Comment by Shariar-Hasan** [comment]
Hello @Trevisx07,
is this design okay ?
![image](https://github.com/user-attachments/assets/4adc3c47-4540-40a7-91b0-e83b6791a648)

**Comment by Trevisx07** [comment]
@Shariar-Hasan Yaa, its pretty good!
