### ISSUE TITLE
[Feat] chat icon should be in end position when there is no scroll to top button

### ISSUE THREAD

**Issue by Shariar-Hasan** [Luson045/medi-connect#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/d947002f-347d-41c4-962d-6db6d2b1d035)
chat icon should be in end position when there is no scroll to top button

### Use Case

- it will provide better user experience in my point of view

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
okay... you can work on it @Shariar-Hasan

**Comment by Luson045** [comment]
@Shariar-Hasan the chatbot is not interactable anymore, the user is not able to give input or close it... plz look into it.

**Comment by Shariar-Hasan** [comment]
but its working from my end in https://med-space.vercel.app/ , can you explain more about, actually what happened?



https://github.com/user-attachments/assets/01bb4cbd-5c86-4130-915e-d77d6363ea5e

**Comment by lade6501** [comment]
> but its working from my end in https://med-space.vercel.app/ , can you explain more about, actually what happened?
> 
>  Screen.Recording.2024-10-13.234530.mp4

Could you change input type color and bot response color to some visible color. It's really hard to see text.

**Comment by Luson045** [comment]
@Shariar-Hasan 
[a57c7d12-3e88-4f20-9e33-964191616a5a.webm](https://github.com/user-attachments/assets/f070009c-9cc4-4eba-8fdf-6595970d4bc3)
see the difference when I'm at the top of the page nothing is clickable, when i scroll down the only i can type and close the chatbot

**Comment by Shariar-Hasan** [comment]
according to the above changes, should i create a PR @Luson045 ?

**Comment by Luson045** [comment]
@Shariar-Hasan okay
fix this too
<img width="236" alt="image" src="https://github.com/user-attachments/assets/ec292dc9-1615-494f-b8bf-a7ae48528a73">
<img width="383" alt="image" src="https://github.com/user-attachments/assets/b6ce4dd4-85c8-4fb4-8f40-396046305a4e">

**Comment by Shariar-Hasan** [comment]
got it

**Comment by Shariar-Hasan** [comment]
@Luson045 

created a PR in #434
