### ISSUE TITLE
[Feat] Dark mode

### ISSUE THREAD

**Issue by nidhi752** [Luson045/medi-connect#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish there was a dark mode feature on the website to enhance the user experience. It would not only improve the overall aesthetics but also make browsing more comfortable, especially in low-light conditions. Dark mode could reduce eye strain and offer a modern, sleek look, making the interface more visually appealing and easier to navigate.

### Use Case

Implementing a dark mode feature would significantly enhance my experience with the project by making prolonged usage much more comfortable, especially during nighttime or in dimly lit environments. It would help reduce eye strain, allowing me to focus on the content for longer periods without discomfort. Additionally, a well-designed dark mode would add a layer of elegance to the interface, creating a more modern and professional look that could improve both usability and overall user satisfaction.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
have you visited the website?
