### ISSUE TITLE
Feature Request: Add Zod Validation to API Endpoints

### ISSUE THREAD

**Issue by 29deepanshutyagi** [Luson045/medi-connect#39]
Currently, the API routes (e.g., /register) accept and handle user input without any structured validation. This could potentially lead to improper or invalid data being passed into the system, which could cause downstream issues in the application (e.g., malformed data in the database).

Proposed Solution:

I recommend integrating [Zod](https://zod.dev/) to handle schema validation for incoming API requests. Zod is a TypeScript-first schema declaration and validation library that makes it easier to enforce data consistency and handle errors in a structured way.

Goals:

    Validate Incoming Data: Apply Zod validation to ensure the incoming request data (e.g., name, age, contact, etc.) meets specific constraints before processing the request.

    Graceful Error Handling: Respond with meaningful error messages if the data does not meet the validation schema.

    Maintain Data Integrity: Ensure that only valid and well-structured data reaches the database.

**Comment by 29deepanshutyagi** [comment]
i want to working on this issue @Luson045 , if you did n't have any issue

**Comment by Luson045** [comment]
currently some people are working on the user authentication part i'd like to add this issue but seperating all of these things would cause decentralization, i'll confirm in a while

**Comment by Luson045** [comment]
consider explaining your ideas here and aligning it with others discussion #40

**Comment by varma-101** [comment]
we are already assigned with authentication. in the issue #36 . can we implement zoi (a node library) for this issue.
