### ISSUE TITLE
[Bug] : User is able to move to next step

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

Currently user is able to go to next step of registration form by click on step number without filling the `required` details in previous step and is able to submit form which throws an validation error from backend. 
Proposed solution would be to add validation on step click to check if required details are fill before moving to next step.

 

### Add Screenshots

https://github.com/user-attachments/assets/a62efd76-5371-40cc-9ac8-a6212a6b8241

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@lade6501 okay you can work on it
