### ISSUE TITLE
[Feat] Add "Check OPD Schedule"

### ISSUE THREAD

**Issue by AdityaBavadekar** [Luson045/medi-connect#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a page for Checking the OPD Schedule which will show at what time which doctors are available. The user can select a department and the corresponding OPD Schedule will be shown.

![image](https://github.com/user-attachments/assets/46190cad-3019-4131-adc9-73b9da5d7e7d)

### Use Case

It may happen that the user is in emergency and cannot wait till the appointment is approved. In that case, the user should be able to see directly, at what time a specific doctor/specialist is available. Also the user might be comfortable with a specific doctor (he might have visited him many times in past and the medication helped every time.)

### Benefits

This benefits the user in case of an emergency, as some times an appointment may or may not be approved.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@AdityaBavadekar if you are working on this issue, then add an option in hospital profile page where hospitals can add doctors and based on that push their slots in the database from the backend and make a new page where users can view hospital details and there we can show this
