### ISSUE TITLE
[Feat] : Add loader during registration 

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently we do not show any action when user clicks on register button which leave user in question whether he/she clicked `Register` button or not and again clicks `Register` button which sends multiple requests to the server  which in return throws a error.  So A loader will give a visual indication of some process and to wait to finish it.

### Use Case

Will help user during registration. 

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
okay @lade6501 that'd be great

**Comment by harshbhar0629** [comment]
Can i work on this issue??
