### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [Luson045/medi-connect#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### Use Case

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@TBorundia it is already there in about page
