### ISSUE TITLE
[Feat] Fix Login Page Header Display and Input Field Height Mismatch

### ISSUE THREAD

**Issue by Md-SabbirHosen** [Luson045/medi-connect#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

***Current UI***
<img width="960" alt="Screenshot 2024-10-12 222035" src="https://github.com/user-attachments/assets/b29fd9dd-00a8-4283-8529-dd184f6d203a">

This issue involves two key improvements to the login page:
1. The login header should be styled more prominently to differentiate it from regular text and look like a proper heading.
2. The user type input field should have the same height as the email and password fields to maintain visual consistency.

### Use Case

Users visiting the login page should be able to easily identify the login header and experience a visually cohesive form layout. Proper alignment of input fields improves the overall UI/UX, making the interface cleaner and easier to use.

### Benefits

- Enhanced visual appeal with a clearly distinguishable login header.
- Improved form consistency, leading to a more polished user experience.
- Increased accessibility by making the form layout more intuitive.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Md-SabbirHosen  👍🏻
