### ISSUE TITLE
Add "Forgot Password" Feature to Login Page

### ISSUE THREAD

**Issue by Mdraza78** [Luson045/medi-connect#41]
Add Forgot password in Login If user Forgot 

Issue:
Currently, there is no option for users to reset their password if they forget it, which can lead to frustration and hinder access to their accounts.

Proposed Solution:
Implement a "Forgot Password" link on the login page. This link should direct users to a password recovery process, where they can enter their registered email address to receive instructions for resetting their password. This enhancement will improve user accessibility and overall experience.

**Comment by Luson045** [comment]
@Mdraza78 thanks for your time but this issue is covered in issue #8
