### ISSUE TITLE
[Bug] : Refactor Files in the Modules Directory for Better Maintainability

### ISSUE THREAD

**Issue by tejasbenibagde** [Luson045/medi-connect#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The current folder structure in the backend is generally well-organized, but the files within the `modules` directory are not maintainable in their current state. To improve readability, scalability, and maintainability, I suggest refactoring the `modules` directory by separating its contents into the following folders:

1. **routes/** - For organizing all API routes.
2. **controllers/** - To handle request logic.
3. **middlewares/** - For middleware functions.
4. **utils/** - To store utility functions.
5. **validations/** - For organizing validation logic.

This refactor will make the codebase cleaner and easier to manage in the long run. However, it will require careful restructuring of existing files and thorough testing to ensure that no functionality breaks during the process.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@tejasbenibagde  why don't you do this at once, you raised three PRs till now for this.

**Comment by tejasbenibagde** [comment]
@Luson045 I know that I did 2 of them already and this is a 3rd one. But you'll have to understand that your backend code is large now. If I try to do all at once It'll have way to many merge conflicts and I might end up making more problems than solving the one that is why I'm doing it in small chunks. But rest be assured this will be my last one related to this problem at least.

**Comment by tejasbenibagde** [comment]
@Luson045 please reply

**Comment by Luson045** [comment]
@tejasbenibagde  okay 👍🏻

**Comment by tejasbenibagde** [comment]
@Luson045 this will be the last time I'll be working on refactoring the code. Next time I'll focus on adding features or removing bugs. :)
