### ISSUE TITLE
[Bug] Registration failed due to incorrect enum declaration

### ISSUE THREAD

**Issue by 17arindam** [Luson045/medi-connect#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

while registering it is giving failed error due to wrong valued passed in payload . Because of which no new user can register 

### Add Screenshots

https://github.com/user-attachments/assets/a8a52843-9e27-4c70-8cf1-451361b0c29c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 17arindam** [comment]
@Luson045 please assign me this issue

**Comment by lade6501** [comment]
Hi @17arindam, just add `transform` property for `gender` in zod validation for this one

**Comment by Luson045** [comment]
@17arindam it's because it should be Male not male, idk who keeps changing this 🤦‍♂️
