### ISSUE TITLE
Adding Style to Login page!

### ISSUE THREAD

**Issue by Shekhar-Raj** [Luson045/medi-connect#42]
I want to change the style of login page for better user performance, like the form format is not made correctly from the user's point of view!

Can You please assign me the issue under gssoc and hacktoberfest-accepted, so that i can  successfully contribute to this project .

Your User page :
![image](https://github.com/user-attachments/assets/0ecc6b44-6f36-4abc-bace-dd6d6e60bf17)

Login Page I want to create:

![image](https://github.com/user-attachments/assets/c193c09b-d76d-46c7-a03d-21e4df1096e6)

**Comment by Luson045** [comment]
please select some other open issue, this issue is covered in issue #8
