### ISSUE TITLE
[Feat] Improve UI of HospitalAround Page with Hospital Info Card and Add Footer Section

### ISSUE THREAD

**Issue by Md-SabbirHosen** [Luson045/medi-connect#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The HospitalAround page currently displays a map showing nearby hospitals. To enhance the user experience and layout, I propose the following changes:
1. Add Hospital Info Card: Place a card over the map containing hospital information and the user's location details (long and lat).
2. Add Footer Section: Include a footer below the map to display additional information, links, or copyright notices.

### Use Case

When users visit the HospitalAround page, they should have quick access to nearby hospital details and their own location in a clean, informative UI. The footer will provide a consistent structure and extra resources without interfering with the map display.

### Benefits

- Improved User Experience: The info card provides easy access to hospital and location information without obstructing the map view.
- Structured Layout: Adding a footer helps with page balance and allows for extra content like links or legal notices.
- Responsive Design: Both the info card and footer will ensure a polished experience on all screen sizes, enhancing usability.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Md-SabbirHosen scroll down and you can see the cards, just bring them over the map, like google maps, and make it user friendly

**Comment by Md-SabbirHosen** [comment]
@Luson045 Please review my #422 pull request.

**Comment by Md-SabbirHosen** [comment]
@Luson045 what about the footer section. I've seen there is no footer section.

**Comment by Luson045** [comment]
@Md-SabbirHosen no need for footer there
