### ISSUE TITLE
[Feat] No back button on blogs pages.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This is not  a good user experience that there is no back button on page and user need to use navbar or web browser default back button.

### Use Case

Enhance user experience.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@VinayLodhi1712 hmm didn't thought about it, you can work on it
