### ISSUE TITLE
[Feat] On map i can show route to the hospital from your location.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can use leaflet library and show user route to the nearest hospital from its location. 
In emergency condition user can use this map to go to the hospitals.
Additional i need time for it to work on as i know it takes time.

it will look like this 

https://github.com/user-attachments/assets/261ce7e1-6b91-4e1c-b94a-de1edf4995e8

if you wanted this kind of feature then we can think about it.

### Use Case

Enhance Functionality of showing hospital on maps and maps feature.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@VinayLodhi1712 
yeah that'd be great, can we do this when user books instant opd, we can show him the route to the hospital he/she was assigned

**Comment by VinayLodhi1712** [comment]
> @VinayLodhi1712 yeah that'd be great, can we do this when user books instant opd, we can show him the route to the hospital he/she was assigned

first let me do this route functionality on map because its just add more functionality to the map page .
then i can work on it because i have to see on things like user has assigned which hospital and then have to show route.

So currently i am thinking on work on route from current location to the different hospitals which are showing on the pages. So if you wanted this so assigned level also in it. Because it also take time.

**Comment by Luson045** [comment]
okay
