### ISSUE TITLE
[Bug] Proceeding to next step without entering any information

### ISSUE THREAD

**Issue by Deekshit7483** [Luson045/medi-connect#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

When the user attempts to proceed to the next step in the form without entering any information, the application still allows them to move forward. This should be prevented by adding proper form validation.

Steps to Reproduce:

Open the form.
Click on "numbers" without entering any data.
The application proceeds to the next step without any validation.

Proposed Solution:
Implement form validation to prevent moving to the next step unless all mandatory fields are completed.

### Add Screenshots

[Screencast from 14-10-24 07:26:07 PM +0530.webm](https://github.com/user-attachments/assets/71653c48-6fc0-4b14-849f-4c33fa4bfe04)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [ ] I want to work on this issue (Optional)
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Keshav-1803** [comment]
I would like to work on this issue under hacktoberfest and gssoc

**Comment by Trevisx07** [comment]
@Deekshit7483 Go with it.

**Comment by lade6501** [comment]
Hi @Trevisx07 / @Deekshit7483  we already have issue for this #392

**Comment by Trevisx07** [comment]
@lade6501 okay you can work on it!

**Comment by Trevisx07** [comment]
@Deekshit7483 No need to do this as he is doing. You can find new issues and comment ensuring that no one took it before.
