### ISSUE TITLE
Design Frontend UI to Display Hospital Cards in Hospitals page

### ISSUE THREAD

**Issue by varma-101** [Luson045/medi-connect#44]
Goals:
Create HospitalCard Component: A reusable component that will display the hospital’s details, such as name, location, contact information, and rating.
Mock Data for UI Testing: Use static mock data to simulate hospital information for development and testing purposes.
Responsive Layout: Ensure the design is responsive and adjusts to various screen sizes.
Styling: Implement modern, clean, and responsive styles using CSS, CSS-in-JS, or a design framework like Material UI or Bootstrap.
API Integration Placeholder: Provide a placeholder in the code where the backend API integration can be added later.

**Comment by Luson045** [comment]
Cool @varma-101  I'll assign this to you in the morning.

**Comment by Luson045** [comment]
@varma-101 updates??

**Comment by varma-101** [comment]
![image](https://github.com/user-attachments/assets/8d640ffb-e927-4c0f-a54f-854ee512004d)
can i make a pr please review it.

**Comment by varma-101** [comment]
These cards are also responsive

**Comment by Luson045** [comment]
okay @varma-101 make sure you have the latest changes in your commit. do not change anything else than the hospital cards

**Comment by AKSHATH99** [comment]
Hey , can i work on the ui improvements and design on this after @varma-101 pushes his latest changes  ?

**Comment by Luson045** [comment]
@AKSHATH99 okay 👍, but explain the changes you want to make

**Comment by AKSHATH99** [comment]
Yeah , i will look into latest changes and raise a issue with my changes

**Comment by varma-101** [comment]
> okay @varma-101 make sure you have the latest changes in your commit. do not change anything else than the hospital cards

ok i didn't changed anything.

**Comment by varma-101** [comment]
ha yes i'll do it shortly and give you update

**Comment by AKSHATH99** [comment]
Alright

**Comment by varma-101** [comment]
I've created a pr please review it i've verified with latest code in this repo until now it's looked fine.

**Comment by varma-101** [comment]
I've changed only 3 files
main index.html to add bootstrap cdn link
HospitalList.jsx & HospitalList.css

**Comment by Luson045** [comment]
@varma-101 can you use tailwind instead of bootstrap?? bootstrap is often very slow to load

**Comment by varma-101** [comment]
> @varma-101 can you use tailwind instead of bootstrap?? bootstrap is often very slow to load

Ok I'll use tailwind.

**Comment by varma-101** [comment]
Bro i've completed it using tailwind css.
![image](https://github.com/user-attachments/assets/977398b8-21d7-4cfb-ac4e-a7984979bb41)

**Comment by Luson045** [comment]
okay give pr will be merged by tomorrow

**Comment by varma-101** [comment]
I already gave pr
