### ISSUE TITLE
[Feat] Add user profile photo the profile page

### ISSUE THREAD

**Issue by AyushSharma72** [Luson045/medi-connect#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add user add profile photo option in the profile page 

please assign this issue to me @Luson045 

### Use Case

![image](https://github.com/user-attachments/assets/62c9ce63-f2dd-4707-b1d5-ae6dbac2e038)

there should be a profile photo with all other information of the user 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
not needed as of now
