### ISSUE TITLE
[Bug] Unnecessary chatbot button occurring 2 times at the bottom

### ISSUE THREAD

**Issue by spc-28** [Luson045/medi-connect#444]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug Description?

After scrolling near the footer there comes the chatbot button 2 times which i think is not required. And also there is a requirement for some css changes in the chatbot.

Please assign this to me so that i can create a PR.

### Add Screenshots

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/6ff6e0d7-db30-4702-ac1b-d339c45dc3b8">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Trevisx07** [comment]
@spc-28 Okay, Solve it.
Try to make a PR within 12 hours.
