### ISSUE TITLE
The section of What Our Patients Say is not looking so good i wanted to change its UI so it will look good.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#45]
![reviewbekar](https://github.com/user-attachments/assets/2a9f6091-27cc-4254-9f13-81e3d603b951)
this is your what our patients say section

I can change it to this type of design. I have made this type of design in my project you can seen this two below image and any of one you suit you can tell me :-
![review](https://github.com/user-attachments/assets/49da8095-3996-4f06-bc53-1ee1a0235a3d)

![another review](https://github.com/user-attachments/assets/790027c5-49e6-4b58-ac06-f8bad050a787)

assign this me under gssoc extended and hactoberfest

**Comment by Luson045** [comment]
@VinayLodhi1712 assigned 👍🏻

**Comment by Luson045** [comment]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/30944e43-9244-4cfa-b3a3-1a56b0936bc6">
the last few reviews are not visible

**Comment by VinayLodhi1712** [comment]
ok that time it is working finely i think some one has change the home page layout so only last review right portion is not showing i will correct it till then wait.

**Comment by VinayLodhi1712** [comment]
now i have changed the layout and it is working fine and create pull request #72 in which it is done
