### ISSUE TITLE
Validation and UI Enhance for OPD Registration Form

### ISSUE THREAD

**Issue by Kunj05** [Luson045/medi-connect#46]
**Description**: The current OPD registration form lacks sufficient validation and user interface enhancements, which can lead to user errors and a suboptimal registration experience.

**Current Behavior:**
The form does not validate user inputs effectively.
The user interface is basic and may not provide an intuitive experience for users.

**Image**
![Screenshot 2024-10-02 015133](https://github.com/user-attachments/assets/39a0d73e-fef9-4525-9fc3-99333a0629c5)

**Proposed Solution**:
I would like to work on implementing input validation and enhancing the UI for the OPD registration form to improve user experience and data accuracy.

Checklist

- [x]  I have checked the existing issues
- [x]  I have read the Contributing Guidelines
- [x]  I'm a GSSoC'24-Extd contributor
- [x]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue

**Comment by Anamika1608** [comment]
Hey , can you pls assign me this issue ?

**Comment by Luson045** [comment]
@Kunj05  sure go for it 👍🏻

**Comment by Luson045** [comment]
@Anamika1608 it's first come first serve
