### ISSUE TITLE
[Feat] : Allow Instant OPD and Feedback feature to user only when they are logged in.

### ISSUE THREAD

**Issue by Ashwinib26** [Luson045/medi-connect#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To restrict **Instant OPD** and **Feedback** features to logged-in users, implement authentication checks that grant access only after user login. ensuring secure access and personalized interaction for **authorized users**.

### Use Case

No garbage entries in database.

### Benefits

  This will ensure secure access and personalized interaction for **authorized users**.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Ashwinib26  no instant OPD is for that purpose only..
