### ISSUE TITLE
[Feat] : Improvements in Lab Test section design

### ISSUE THREAD

**Issue by Ashwinib26** [Luson045/medi-connect#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improve Lab Test section with clear categories, search and filters, detailed test info, transparent pricing, personalized recommendations(*) , and quick support access(Comments section).

### Use Case

The **Lab Test section** allows users to search and track lab tests effortlessly, view detailed info and access test history, ensuring a seamless healthcare experience.

### Benefits

Visually appealing website would attract Users.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
@Ashwinib26 not needed
