### ISSUE TITLE
[Feat] Add a Translation Tool (all language) ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Luson045/medi-connect#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Translation Tool(all language) properly.

@Luson045 PA please assign me this task.

![Screenshot 2024-10-20 212427](https://github.com/user-attachments/assets/7189eb11-0602-4727-ab32-99892261547d)

### Use Case

..

### Benefits

..

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Jashwanth-rit** [comment]
checkout , footer , it already exists. @Subhajit-2023-44

**Comment by Luson045** [comment]
@Subhajit-2023-44  don't spam

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 don't spam

what ??
