### ISSUE TITLE
Add Table to Display Repository Statistics in README.md

### ISSUE THREAD

**Issue by amiya-cyber** [Luson045/medi-connect#543]
Issue Description:
The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions at a glance.

Steps to Implement:

- Create a table in the README.md file displaying the following repository statistics:
- Stars
- Forks
- Open Issues
- Open Pull Requests
- Closed Pull Requests
- Use markdown syntax to include badges or icons for each statistic.
- Add dynamic links to the corresponding sections of the repository for easy access (e.g., link to the "Issues" or "Pull Requests" tabs).

Expected Behavior:

The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

Screenshot (for reference):
![2024-10-25 (9)](https://github.com/user-attachments/assets/2bfec824-8782-4743-a16b-5e9bc38b8588)

ADD ALL THE LABELS
LEVEL 2 OR LEVEL 3
HACKTOBERFEST
GSSOC EXT
PLEASE ASSIGN ME
THANK YOU @Luson045

**Comment by Luson045** [comment]
@amiya-cyber it's not permitted to give level 1 on documentation issues, if you don't want to take on with level 1 then kindly close the issue
