### ISSUE TITLE
[Feat] Enhance UI of navbar 

### ISSUE THREAD

**Issue by SumaLatha2023** [Luson045/medi-connect#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar has limited navigation options and lacks hover effects. 
Enhancing it by adding a new page link, positioning the theme toggler at the right end, and including hover effects will improve navigation clarity and usability. 
This change is essential for a more intuitive user experience and a modern, polished design.

### Use Case

Users can access additional pages through a more intuitive, organized navbar, and easily toggle between themes from the right-end position. Hover effects will provide visual feedback, enhancing navigation clarity.

### Benefits

Improves usability with a well-organized layout and accessible theme control.
Enhances user experience with responsive, engaging hover effects.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by SumaLatha2023** [comment]
@Luson045 Kindly assign me this issue with relevant labels

**Comment by Luson045** [comment]
no work on navbar to be done now
