### ISSUE TITLE
make navbar item colored on the basis of which item is selected

### ISSUE THREAD

**Issue by shivamy009** [Luson045/medi-connect#55]
make navbar more functional

**Comment by xauravww** [comment]
Hi,I'd like to work on this issue. Could you please assign it to me with peoper labels? Also , can u share more details ?
Thanks!

**Comment by Luson045** [comment]
Navbar issue covers this one, if it is not covered. I'll assign

**Comment by Luson045** [comment]
@xauravww  please consider asking to assign on issues raised by the admins or raise your own issues, as it's first come first serve, I cannot assign someone, unless the author is not capable of solving it.

**Comment by Luson045** [comment]
It's first come first serve @Himanshu0325

**Comment by Himanshu0325** [comment]
> It's first come first serve @Himanshu0325

bro don't mind my words but it should not be first come fisrt serve 
u should assign base on skill check my profile

**Comment by Luson045** [comment]
@Himanshu0325 well that's under GSSoC's policy. If I were not to follow those, I wouldn't have let the contributors open similar type of issues again and again.

**Comment by Himanshu0325** [comment]
> @Himanshu0325 well that's under GSSoC's policy. If I were not to follow those, I wouldn't have let the contributors open similar type of issues again and again.

Ok
