### ISSUE TITLE
[Feat] Creating the our doctors page

### ISSUE THREAD

**Issue by Jay-1409** [Luson045/medi-connect#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The idea is to complete the "Our Doctors page"
The page description:
- Contain top doctor cards
- Conrain the treatment category
- Contain the rating of doctor (Additional feature)
- contain book appointment button

### Use Case

Help the user view through top doctors and choose.

### Benefits

Ease of access 

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
not needed as of now
