### ISSUE TITLE
[Feat] Darker text under disclimer

### ISSUE THREAD

**Issue by A2005-beep** [Luson045/medi-connect#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the home page, under 'DISCLIMER' section the text is very light and cant be read if the light theme is on. 
![Screenshot (7)](https://github.com/user-attachments/assets/21d5197f-dd8c-473c-ab83-e076955ba01e)

### Use Case

I would suggest making that text with a dark color which can be easily read. @Luson045 

### Benefits

It will be easy to read the disclimer in the light theme also

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
work is going on
