### ISSUE TITLE
[Bug] text not visible in footer

### ISSUE THREAD

**Issue by Gauravtb2253** [Luson045/medi-connect#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The Med Space text in footer is not clearly visible due to gradient effects
Also the disclaimer is not visible

### Add Screenshots

![image](https://github.com/user-attachments/assets/c17a6c12-a41e-467a-97c3-ddb02d8110f3)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
work is going on
