### ISSUE TITLE
[Bug🐞]: Change Hospital Page Background Color 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Luson045/medi-connect#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

The hospital page background color does not change and remains the same even after switching to dark theme.

### Add Screenshots

![image](https://github.com/user-attachments/assets/9b07aeb8-9efa-4396-b67d-4d5c9abbf203)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Luson045** [comment]
ahh, do it in the previous issue[ervice page dark mode], I've already added level2 to it.
