### ISSUE TITLE
Redesigning the Review section

### ISSUE THREAD

**Issue by ayush-848** [Luson045/medi-connect#58]
![image](https://github.com/user-attachments/assets/0dd2b954-8a21-4e29-bbef-a6ebf0e4b0d8)

**Comment by ayush-848** [comment]
@Luson045 please see this one. And do let me know if I can change the background too

**Comment by Luson045** [comment]
It is also covered by someone, please check the existing issues

**Comment by ayush-848** [comment]
> It is also covered by someone, please check the existing issues

I searched for Our Services and didn't see an issue open

**Comment by Luson045** [comment]
issue #28

**Comment by ayush-848** [comment]
> issue #28

So can i do the testimonial part
I can add images too

**Comment by Luson045** [comment]
see if you can make it look very professional, complete it and send screenshot, if it is really good, then ill assign you and add labels

**Comment by ayush-848** [comment]
> see if you can make it look very professional, complete it and send screenshot, if it is really good, then ill assign you and add labels

Ok
