### ISSUE TITLE
Redesign the home page using react

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#6]
I want to redesign the frontend, to make it look really professional

**Comment by CFokstuen** [comment]
Some feedback: A complete redesign and build of your UI is likely not a good first issue.

**Comment by Luson045** [comment]
Ok

**Comment by SuperexMack** [comment]
i can work here but sorry i am confused that which part of the frontend to redesign , The whole frontend?

**Comment by Luson045** [comment]
just the home.jsx file that is the landing page... this page(https://medi-connect-in.netlify.app/), like resize the graphs, use better cards, etc and all that to make it look professional, you can also use tailwind but make sure to initilize it as we haven't added any tailwind component yet, but it's your choice.

**Comment by SuperexMack** [comment]
okh sir , done 🫡 will try my best to redesign it . will report u soon

**Comment by Luson045** [comment]
cool 👍

**Comment by SuperexMack** [comment]
![Screenshot 2024-09-30 224642](https://github.com/user-attachments/assets/ad129ff2-88dd-4cbd-98cf-cf2844b4ec3b)

Could you let me know how this looks so far? We've just worked on the basics for now, and we'll be refining it further. Your feedback at this stage would be really helpful.

**Comment by Luson045** [comment]
already looking great bro, I think the bright blue gradient could be just a little more lighter, overall the fonts and colors are looking great 👍

**Comment by SuperexMack** [comment]
Oh thanks @Luson045 , yeah i am thinking to change the whole landing page so it will took about 1-2 days.

**Comment by SuperexMack** [comment]
https://github.com/user-attachments/assets/e1095e89-c273-43b6-96b1-ae6b8ccf53aa

I’ve made some updates, and since it’s my first time contributing, I’m a bit confused. Could you please check the entire section and this video? I would appreciate your feedback on what I can improve. Thank you!

**Comment by Luson045** [comment]
@SuperexMack the text inside the service cards and user feedback cards should be properly visible. I think you can  use different colour for the text inside the box and do you think a light theme would look better? 🤔

**Comment by SuperexMack** [comment]
okh done 
will implement a light theme and will fix that visibility too 
just give me some time :)

**Comment by SuperexMack** [comment]
https://github.com/user-attachments/assets/9d605a9c-2664-4419-9b39-cd3e1aeada3b

Sir, I’ve tried implementing a few things. I know it’s not looking great at the moment—just some simple changes. Could you help me with some ideas on what our page should look like? I have a few ideas in mind, but I’m not sure if they’re worth implementing. Your guidance would be really helpful!

**Comment by Luson045** [comment]
@SuperexMack the colour combination is looking great now, since it is targeting the Indian public, I guess we should keep it light themed like this one, overall it's looking great, but check the responsiveness, and I guess you can add some images and stuffs and animations, but it's up to you, the current changes you made  is what I expected from this issue, so you can add some more stuffs, what I mentioned above, but even you give PR with these changes, its acceptable.

**Comment by SuperexMack** [comment]
ooh thanks for the feedback .
yeah now i wanna work on responsiveness first and after that i will to create some animation too .

**Comment by Luson045** [comment]
you can join the discussion with other contributors to get more ideas and thoghts

**Comment by SuperexMack** [comment]
https://github.com/user-attachments/assets/8403b8fc-7036-4aa4-b1bb-8c44f739a5a3

sir this is the final look i added some basic scrolling animations and made it responsive , are u satisfied or i have to make more changes?

**Comment by Luson045** [comment]
great job, you can give the PR

**Comment by Luson045** [comment]
this issue is completed
