### ISSUE TITLE
Implement the backend of instant opd in frontend

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#66]
<img width="987" alt="image" src="https://github.com/user-attachments/assets/7529930b-1292-436b-9331-00006fc36c41">

This is the screenshot you may check it out

_Originally posted by @tanish35 in https://github.com/Luson045/medi-connect/issues/63#issuecomment-2387749832_
            
work on the instant opd page that will send this format of data and recieve the data on the left side in email and text message

**Comment by lade6501** [comment]
Hi @Luson045 can I work on this.

**Comment by Somnath-Chattaraj** [comment]
since i worked on it can i get assigned

**Comment by Luson045** [comment]
@Somnath-Chattaraj @lade6501 both of you can go with it

**Comment by Somnath-Chattaraj** [comment]
@lade6501  you please do the text message and i will work on the email.

**Comment by lade6501** [comment]
Sure @Somnath-Chattaraj
