### ISSUE TITLE
issues in instant OPD feature

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#68]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/f9433a54-38f4-4458-8572-f234f066a8ec">

just fix the bug and make it work

**Comment by Luson045** [comment]
take a look at age, gender and symptoms i guess that's the issue

**Comment by guruprasath-v** [comment]
@Luson045 I would like to work on this issue. Please assign me this issue under hacktoberfest

**Comment by Luson045** [comment]
@guruprasath-v  sorry for keeping this, it is fixed
