### ISSUE TITLE
Register link in Navbar does not redirect to Register Page

### ISSUE THREAD

**Issue by lade6501** [Luson045/medi-connect#70]
**Bug**
  When we click on the Register link on nav bar, it does not redirect's to `Register Page` instead it loads the `Login` page only 

**Expected behaviour**
When we click on the Register link on nav bar, it should load `Register` page/component.

https://github.com/user-attachments/assets/df6cd4fb-610e-430a-9253-2b56afad59b8

**Comment by Luson045** [comment]
hmm actually there is only this single file for register and login, you can try to seperate it but make sure none of the operation is hampered

**Comment by Luson045** [comment]
@lade adding on to this issue can you change the registration form according to the details required for the hospital and users

as both hospital and user have different fields i their database, we need to handle taking those details when a hospital or a user registers... You can find the required fields in server/model  just add input for the items which are there in the model but not in the UI

example we need to take input of PIN code from the user but it is not there in the register page as of now..

first  you can merge conflicts of your previous pr and then you can do this one

**Comment by lade6501** [comment]
Sure, will make the changes.

**Comment by lade6501** [comment]
> @lade adding on to this issue can you change the registration form according to the details required for the hospital and users
> 
> as both hospital and user have different fields i their database, we need to handle taking those details when a hospital or a user registers... You can find the required fields in server/model just add input for the items which are there in the model but not in the UI
> 
> example we need to take input of PIN code from the user but it is not there in the register page as of now..
> 
> first you can merge conflicts of your previous pr and then you can do this one

Hi @Luson045 so this changes will be part of this issue or we can create new from this discussion.
