### ISSUE TITLE
Layout of Login Page

### ISSUE THREAD

**Issue by snehhhcodes** [Luson045/medi-connect#74]
Hello there!!

I hope this message finds you well. I would like to address an issue I encountered on the website and propose a solution that I believe will enhance the website.

Description of Issue:

 I think the login page has an unorganized layout, with input fields and buttons positioned awkwardly. This lack of visual appeal makes the page less engaging and does not reflect a professional design, which could affect user experience.

Proposed Solution:

To resolve this issue, I will rearrange the elements to achieve better alignment and ensure consistent spacing between the input fields and buttons. Additionally, I will optimize the overall layout to create a cleaner and more visually appealing appearance, enhancing the overall user experience.

I am attaching a visual for you to view the issue clearly.
![Screenshot 2024-10-02 150413](https://github.com/user-attachments/assets/46cde4c7-ba0f-44a9-b321-d4a23a4206fe)

If you find this proposal suitable, I would appreciate it if you could assign these tasks to me.
Looking forward to your feedback! Thank you!

**Comment by Luson045** [comment]
It's already worked on
