### ISSUE TITLE
"Form validation" for "Sign up page"

### ISSUE THREAD

**Issue by clownfish1805** [Luson045/medi-connect#78]
![image](https://github.com/user-attachments/assets/fd8e3e74-9669-4fd1-a556-4910bf4fab12)

@Luson045 
The form validation on the sign-up page does not provide specific error messages when users attempt to register with incorrect or incomplete information. Upon clicking the "Register" button, the form triggers a validation error, but it does not inform the user about what fields are causing the issue (e.g., invalid email format, missing required fields, weak password).

Expected Behavior:
When a user clicks "Register" with incorrect or incomplete information, specific error messages should be displayed for each problematic field.
**Email field**: Should show an error if the format is invalid (e.g., "Please enter a valid email address").
**Password field**: Should provide feedback for weak passwords (e.g., "Password must be at least 8 characters long").
**Required fields**: Should show an error if any required field is left empty (e.g., "This field is required").

If validation error ,  then its should mention the reason like passwords doesn't match , etc

**Comment by clownfish1805** [comment]
@Luson045 I would like to work on this issue. Please assign me this issue under **hacktoberfest and GSSOC'24 extended**.

**Comment by Luson045** [comment]
okay assigned 👍
