### ISSUE TITLE
Design the login page and add features like email verification and forget password

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#8]
<img width="638" alt="image" src="https://github.com/user-attachments/assets/f22acb20-f425-4077-9388-b751640dedb8">
<img width="960" alt="login_page" src="https://github.com/user-attachments/assets/577ceb37-e4ac-461b-924c-b1ff981a67f8">

above is the component for login and register page and below it is the login and register page

design this component to make it llok professional and responsive.
Make sure no api call is changed

**Comment by prathmesh703** [comment]
@Luson045 I would like to work on this, can you assign this issue #8 to me

**Comment by Luson045** [comment]
@prathmesh703 i've assigned it to you, if you need any help feel free to drop me a text 👍

for reference to setup, you can check the readme.md and contribution.md files

since you're working on the frontend you need not setup backend, but it's upto you, as the deployed server is on render and it gives slow responses sometimes

**Comment by Luson045** [comment]
nice 👍, check if it's responsive, and one more thing to do, check out discussion #12 and change the colours accordingly

**Comment by prathmesh703** [comment]
I have made it responsive , once the ui colors are fixed ,I will make changes according to it

**Comment by Luson045** [comment]
@prathmesh703  I've shared the video of the UI colour combination in discussion #12 you can take reference from tht

**Comment by shibasarkar** [comment]
@Luson045 I think we can enhace the page a little bit more professionally and also redesign the navbar

**Comment by Luson045** [comment]
@shibasarkar we got that covered in issue #14 for now you can do the backend of login, where we can send email to  users when they forget email and you can also try creating a remember me feature using cache.

**Comment by shibasarkar** [comment]
@Luson045 you mean when a user forgets his password we send an email to the user to reset the password?

**Comment by Luson045** [comment]
Yes

**Comment by Luson045** [comment]
@shibasarkar [IMPORTANT] consider explaining your ideas here and aligning it with others discussion #40 
@prathmesh703 YOU CAN SKIP

**Comment by prathmesh703** [comment]
https://github.com/user-attachments/assets/1612a330-d517-43db-955c-e452a30cb608

@Luson045  is  this ok?

**Comment by Luson045** [comment]
Yeah nice 👍🏻, you can give the PR

**Comment by shibasarkar** [comment]
Is thik ok 
![Screenshot 2024-10-02 205016](https://github.com/user-attachments/assets/2240d783-adc2-411d-a3da-b986cd5d8ea0)

**Comment by Luson045** [comment]
in the register option for the hospitals, add an option for pincode, if you want, i can give level3 if you also cover the backend part of pincode where when a hospital registers it enters the pincode, and there's an api we're using you can search for that in the server, use it and convert the pincode to lat and long and assign these values to that particular hospital data

**Comment by tanish35** [comment]
Can you assign me this where the upon registering the pincode of the hospital gets converted to lat long as I have already worked on this

**Comment by Luson045** [comment]
@tanish35 okay you can do the pincode thing.. but first let @shibasarkar give the pr

**Comment by Luson045** [comment]
@shibasarkar give pr of whatever is completed as of now

**Comment by tanish35** [comment]
@Luson045 can i start the work with this

**Comment by Luson045** [comment]
@tanish35 yes you can 👍🏻
