### ISSUE TITLE
Fix ZOD AUTHENTICATION

### ISSUE THREAD

**Issue by Luson045** [Luson045/medi-connect#92]
ZOD authentication is giving a lot of unwanted issues, fix it if anyone can

**Comment by harish08102004** [comment]
Hey @Luson045 I can work on this.

**Comment by Luson045** [comment]
@Abhi0049k assigned 👍, do you want any help from @harish08102004 , @harish08102004 you can ask him

**Comment by Luson045** [comment]
make sure that you dont change the functioning of the current api's and dont make changes in environment variable names

**Comment by harish08102004** [comment]
Hey @Abhi0049k  text me if need any help.

**Comment by Abhi0049k** [comment]
> Hey @Abhi0049k text me if need any help.

surely

**Comment by Abhi0049k** [comment]
Hi @Luson045, I didn't encounter any Zod errors during authentication, but I did face an error while registering for the online OPD. Is that the error(an error while registering for the online OPD) for which this issue is about?

**Comment by Luson045** [comment]
well actually a lot of people were working on the login and register page so someone might have fixed that,, yea there's an axios error in instant OPD right now, like axios fails sometime
like every alternate time it fails
<img width="741" alt="image" src="https://github.com/user-attachments/assets/47e34788-b874-480e-a69d-13b3ab8138a5">
you can fix this and please be fast else others are very fast to fix issues through other issues 😅

**Comment by Abhi0049k** [comment]
@Luson045 okay, got it
