### ISSUE TITLE
On login and Register page there is not password visible option which is not a good user experience 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Luson045/medi-connect#93]
I want to add an icon fa-eye which helps user to see the password which he/she is inserting.

enhance user experience and help to check user password visibility while filling password.

![againpassword](https://github.com/user-attachments/assets/b91b7e97-8769-4a86-95d9-9a35a3df0453)

after my changes it look like

![done](https://github.com/user-attachments/assets/9feaff90-5623-4b5a-a40c-85630a45eb1b)

**Comment by Luson045** [comment]
assinged 👍
