### ISSUE TITLE
FEATURE: Automated Greeting Workflow 

### ISSUE THREAD

**Issue by harish08102004** [Luson045/medi-connect#94]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @Luson045 please assign me this task.

**Comment by Luson045** [comment]
great idea 👍, assigned!

**Comment by harish08102004** [comment]
Hey @Luson045 I have raised the PR please check and merge.

**Comment by Luson045** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/860c0935-0e44-43f0-bd4f-945cfe383b42">
workflow failing @harish08102004

**Comment by harish08102004** [comment]
Oh ok let me check

**Comment by harish08102004** [comment]
I have made changes in this PR check if it working now
https://github.com/Luson045/medi-connect/pull/115
