### ISSUE TITLE
Fixing Navbar Ui

### ISSUE THREAD

**Issue by Speedysays01** [Luson045/medi-connect#95]
There seem to be some alignment issues for tabs in navbar . I could fix those and can make navigation bar stay at top at all times!
please assign me this issue under Hacktoberfest2024.

**Comment by ROKUMATE** [comment]
@Speedysays01 sure ... I will assign you this issue now ... 

try to complete it by the end of day for tmrr [4th Oct]

**Comment by deji-ice** [comment]
hi, can i collaborate on this issue?

**Comment by Luson045** [comment]
@deji-ice  you can work on it under issue #118 
fix this too
<img width="214" alt="image" src="https://github.com/user-attachments/assets/3422ff43-8763-4bfe-b741-a3fdd0cbd5cb">

**Comment by Luson045** [comment]
@Speedysays01 
no icons in these? it's actually ruining the uniformity add icons in these too and revmove the underline on hover
<img width="960" alt="image" src="https://github.com/user-attachments/assets/3b1cd5b6-4c83-4929-ad9d-83d4e9d2dad6">

**Comment by deji-ice** [comment]
> @deji-ice you can work on it under issue #118 fix this too <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/131430087/373370152-3422ff43-8763-4bfe-b741-a3fdd0cbd5cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODE2NjcsIm5iZiI6MTcyNzk4MTM2NywicGF0aCI6Ii8xMzE0MzAwODcvMzczMzcwMTUyLTM0MjJmZjQzLTg3NjMtNGJmZS1iNzQxLWEzZmRkMGNiZDVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGNiNzYxYzEzZGRlOTAxNmFjMzJlMTAwZjFjOGM2NDRmNDFmNzU1ZWJkNzkxNDNmYjQ0YjUwNzg0YmM3M2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PxA4Ed5vBsS_i42PcXH7bhco_B6sQ9kzxnYlNcBd6po">

alright
