### ISSUE TITLE
Adding Docker File

### ISSUE THREAD

**Issue by TheAdich** [Luson045/medi-connect#99]
Hi

I want to add  Dockerfile to your project because

Integrating Docker will streamline local setup, eliminate manual configuration, and ensure a consistent environment. It will help new contributors get started quickly and focus on building features, enhancing collaboration and efficiency.

Additionally, containerizing the application will make future deployment and scaling much smoother. I'm well-versed with Docker, so I can help set up the configurations and guide the integration process . If it sounded good to you, i am willing to contribute to it as soon as the issue is assigned to me .

**Comment by Luson045** [comment]
i was also thinking to dockerize this repo, to make it easier to setup, though i am not very well versed with docker, so can you explain if dockerizing will add any further dependencies? and if yes,  make the required changes in the README and CONTRIBUTION files.

**Comment by TheAdich** [comment]
No, dockerizing will not add any further dependencies. It will use the images available on Docker Hub and install your project dependencies when run. Thanks for assigning this issue to me. I will complete it as soon as possible.
